import { Medicine, Company, BlogPost, Category } from "./types";

export const categories: Category[] = [
  { id: "1", name: "Antibiotics", icon: "Shield", description: "Fight bacterial infections", count: 245 },
  { id: "2", name: "Pain Relief", icon: "Zap", description: "Manage pain effectively", count: 189 },
  { id: "3", name: "Diabetes", icon: "Activity", description: "Control blood sugar levels", count: 156 },
  { id: "4", name: "Heart Care", icon: "Heart", description: "Cardiovascular health", count: 134 },
  { id: "5", name: "Vitamins", icon: "Sun", description: "Essential supplements", count: 210 },
  { id: "6", name: "Skin Care", icon: "Sparkles", description: "Dermatological treatments", count: 178 },
  { id: "7", name: "Gastric", icon: "CircleDot", description: "Digestive health solutions", count: 145 },
  { id: "8", name: "Allergy", icon: "Wind", description: "Allergy relief medicines", count: 98 },
  { id: "9", name: "Fever", icon: "Thermometer", description: "Temperature management", count: 167 },
  { id: "10", name: "Children Care", icon: "Baby", description: "Pediatric medicines", count: 123 },
];

export const medicines: Medicine[] = [
  {
    id: "1",
    medicine_name: "Napa Extra",
    generic_name: "Paracetamol + Caffeine",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Pain Relief",
    type: "Tablet",
    description: "Napa Extra is a combination of Paracetamol and Caffeine used for the relief of mild to moderate pain including headache, migraine, toothache, period pain, and cold & flu symptoms.",
    usage: "Used for temporary relief of mild to moderate pain and fever. Effective for headache, muscle ache, backache, toothache, menstrual cramps, and arthritis pain.",
    dosage: {
      adult: "1-2 tablets every 4-6 hours as needed. Maximum 8 tablets in 24 hours.",
      child: "Not recommended for children under 12 years without medical advice.",
      elderly: "1 tablet every 6-8 hours. Maximum 4 tablets in 24 hours.",
      special_instructions: "Take with a full glass of water. Can be taken with or without food.",
    },
    side_effects: {
      common: ["Nausea", "Stomach upset", "Dizziness", "Insomnia (due to caffeine)"],
      serious: ["Allergic reaction", "Liver damage (with overdose)", "Severe skin reaction", "Blood disorders"],
    },
    precautions: {
      pregnancy: "Consult doctor before use during pregnancy. Category B drug.",
      kidney: "Use with caution in patients with kidney impairment. Dose adjustment may be needed.",
      liver: "Avoid in severe liver disease. Maximum 2g/day in liver impairment.",
      allergy: "Do not use if allergic to paracetamol or caffeine.",
      drug_interaction: "May interact with warfarin, metoclopramide, and cholestyramine.",
    },
    who_should_avoid: [
      "Patients with severe liver disease",
      "Those allergic to paracetamol or caffeine",
      "Chronic alcohol users",
      "Patients taking other paracetamol-containing products",
    ],
    storage: ["Store below 25°C", "Keep away from sunlight", "Keep away from children", "Store in dry place"],
    price: { unit_price: 2.5, strip_price: 25, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/napa-extra.png",
    alternatives: ["2", "3"],
    created_at: "2025-01-15",
  },
  {
    id: "2",
    medicine_name: "Ace Plus",
    generic_name: "Paracetamol + Caffeine",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Pain Relief",
    type: "Tablet",
    description: "Ace Plus provides effective relief from pain and fever with the combination of Paracetamol and Caffeine for enhanced analgesic effect.",
    usage: "Indicated for temporary relief of mild to moderate pain associated with headache, cold, toothache, muscular aches, menstrual periods, and minor arthritis pain.",
    dosage: {
      adult: "1-2 tablets every 4-6 hours. Maximum 8 tablets per day.",
      child: "Not recommended below 12 years.",
      elderly: "Reduced dose recommended. 1 tablet every 6 hours.",
      special_instructions: "Do not exceed recommended dose. Take with water.",
    },
    side_effects: {
      common: ["Nausea", "Vomiting", "Constipation"],
      serious: ["Hepatotoxicity", "Thrombocytopenia", "Anaphylaxis"],
    },
    precautions: {
      pregnancy: "Use only if clearly needed. Consult physician.",
      kidney: "Caution in renal impairment.",
      liver: "Contraindicated in severe hepatic impairment.",
      allergy: "Avoid if hypersensitive to any component.",
      drug_interaction: "Caution with anticoagulants and hepatotoxic drugs.",
    },
    who_should_avoid: ["Severe liver disease patients", "Known hypersensitivity"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/ace-plus.png",
    alternatives: ["1", "3"],
    created_at: "2025-01-10",
  },
  {
    id: "3",
    medicine_name: "Sergel 20",
    generic_name: "Omeprazole",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Gastric",
    type: "Capsule",
    description: "Sergel 20 is a proton pump inhibitor used to treat gastroesophageal reflux disease (GERD), gastric ulcers, and other acid-related disorders.",
    usage: "Treatment of duodenal ulcer, gastric ulcer, reflux esophagitis, and Zollinger-Ellison syndrome. Also used for H. pylori eradication in combination therapy.",
    dosage: {
      adult: "20mg once daily before breakfast for 2-8 weeks.",
      child: "10-20mg once daily based on weight. Consult pediatrician.",
      elderly: "No dose adjustment required.",
      special_instructions: "Take 30 minutes before meals. Swallow whole, do not crush or chew.",
    },
    side_effects: {
      common: ["Headache", "Diarrhea", "Nausea", "Abdominal pain", "Flatulence"],
      serious: ["C. difficile infection", "Bone fractures with long-term use", "Hypomagnesemia", "Vitamin B12 deficiency"],
    },
    precautions: {
      pregnancy: "Category C. Use only if potential benefit justifies risk.",
      kidney: "No dose adjustment in mild-moderate impairment.",
      liver: "Maximum 20mg/day in severe hepatic impairment.",
      allergy: "Avoid if allergic to proton pump inhibitors.",
      drug_interaction: "May interact with clopidogrel, methotrexate, and ketoconazole.",
    },
    who_should_avoid: ["Patients with known PPI allergy", "Those taking rilpivirine"],
    storage: ["Store below 25°C", "Protect from light and moisture", "Keep away from children"],
    price: { unit_price: 6.0, strip_price: 84, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/sergel.png",
    alternatives: ["7"],
    created_at: "2025-02-01",
  },
  {
    id: "4",
    medicine_name: "Zimax 500",
    generic_name: "Azithromycin",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Antibiotics",
    type: "Tablet",
    description: "Zimax 500 is a broad-spectrum macrolide antibiotic used to treat various bacterial infections including respiratory tract, skin, and soft tissue infections.",
    usage: "Treatment of upper and lower respiratory tract infections, skin and soft tissue infections, otitis media, and sexually transmitted diseases.",
    dosage: {
      adult: "500mg once daily for 3 days, or 500mg on day 1 followed by 250mg on days 2-5.",
      child: "10mg/kg once daily for 3 days. Maximum 500mg/day.",
      elderly: "No dose adjustment required with normal renal function.",
      special_instructions: "Take 1 hour before or 2 hours after meals. Complete the full course.",
    },
    side_effects: {
      common: ["Diarrhea", "Nausea", "Abdominal pain", "Vomiting"],
      serious: ["QT prolongation", "Hepatotoxicity", "Clostridium difficile colitis", "Severe allergic reactions"],
    },
    precautions: {
      pregnancy: "Category B. Use only if clearly needed.",
      kidney: "Caution in severe renal impairment.",
      liver: "Avoid in severe hepatic disease.",
      allergy: "Contraindicated in macrolide allergy.",
      drug_interaction: "May interact with antacids, warfarin, and digoxin.",
    },
    who_should_avoid: ["Patients allergic to macrolides", "Severe liver disease", "History of QT prolongation"],
    storage: ["Store below 30°C", "Keep in original packaging", "Away from children"],
    price: { unit_price: 30.0, strip_price: 90, currency: "BDT", updated_date: "2025-05-10" },
    image: "/medicines/zimax.png",
    alternatives: ["5"],
    created_at: "2025-01-20",
  },
  {
    id: "5",
    medicine_name: "Azicin 500",
    generic_name: "Azithromycin",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Antibiotics",
    type: "Tablet",
    description: "Azicin is a macrolide antibiotic effective against a wide range of gram-positive and gram-negative bacteria.",
    usage: "Used for treating bacterial infections of the respiratory tract, ear, skin, and urogenital tract.",
    dosage: {
      adult: "500mg once daily for 3 days.",
      child: "10mg/kg/day for 3 days.",
      elderly: "Standard adult dose with normal organ function.",
      special_instructions: "Take on empty stomach for best absorption.",
    },
    side_effects: {
      common: ["Diarrhea", "Nausea", "Abdominal cramps"],
      serious: ["Liver dysfunction", "Cardiac arrhythmias", "Angioedema"],
    },
    precautions: {
      pregnancy: "Consult doctor. Category B.",
      kidney: "Use with caution.",
      liver: "Monitor liver function.",
      allergy: "Avoid in macrolide hypersensitivity.",
      drug_interaction: "Avoid with ergot alkaloids.",
    },
    who_should_avoid: ["Macrolide-allergic patients", "Severe hepatic impairment"],
    storage: ["Store below 30°C", "Protect from moisture"],
    price: { unit_price: 25.0, strip_price: 75, currency: "BDT", updated_date: "2025-05-12" },
    image: "/medicines/azicin.png",
    alternatives: ["4"],
    created_at: "2025-02-05",
  },
  {
    id: "6",
    medicine_name: "Losectil 20",
    generic_name: "Omeprazole",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Gastric",
    type: "Capsule",
    description: "Losectil is a proton pump inhibitor that reduces gastric acid secretion for the treatment of acid-related gastrointestinal disorders.",
    usage: "Treatment of peptic ulcers, GERD, and acid hypersecretory conditions.",
    dosage: {
      adult: "20mg once daily for 4-8 weeks.",
      child: "Based on body weight. Consult pediatrician.",
      elderly: "Standard dose. No adjustment needed.",
      special_instructions: "Take before breakfast. Do not crush capsules.",
    },
    side_effects: {
      common: ["Headache", "Nausea", "Diarrhea", "Constipation"],
      serious: ["Interstitial nephritis", "Bone fractures", "Hypomagnesemia"],
    },
    precautions: {
      pregnancy: "Use only when clearly needed.",
      kidney: "No dose adjustment for mild impairment.",
      liver: "Reduce dose in severe hepatic impairment.",
      allergy: "Avoid in PPI allergy.",
      drug_interaction: "Interacts with clopidogrel and phenytoin.",
    },
    who_should_avoid: ["PPI-allergic patients"],
    storage: ["Store below 25°C", "Protect from light"],
    price: { unit_price: 5.0, strip_price: 70, currency: "BDT", updated_date: "2025-05-14" },
    image: "/medicines/losectil.png",
    alternatives: ["3"],
    created_at: "2025-02-10",
  },
  {
    id: "7",
    medicine_name: "Neuro-B",
    generic_name: "Vitamin B1 + B6 + B12",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Vitamins",
    type: "Tablet",
    description: "Neuro-B is a combination of essential B vitamins that supports nerve health and helps prevent vitamin B deficiency.",
    usage: "Prevention and treatment of Vitamin B deficiency. Supports nerve function, energy metabolism, and red blood cell formation.",
    dosage: {
      adult: "1-2 tablets daily after meals.",
      child: "As directed by physician.",
      elderly: "1 tablet daily.",
      special_instructions: "Take with food for better absorption.",
    },
    side_effects: {
      common: ["Mild stomach upset", "Nausea"],
      serious: ["Allergic reactions (rare)", "Peripheral neuropathy with excessive B6"],
    },
    precautions: {
      pregnancy: "Generally safe. Consult doctor for appropriate dose.",
      kidney: "Safe in normal doses.",
      liver: "Safe in normal doses.",
      allergy: "Avoid if allergic to any B vitamin.",
      drug_interaction: "May interact with levodopa and phenytoin.",
    },
    who_should_avoid: ["Those allergic to B vitamins"],
    storage: ["Store below 30°C", "Protect from light and moisture"],
    price: { unit_price: 3.5, strip_price: 105, currency: "BDT", updated_date: "2025-05-16" },
    image: "/medicines/neuro-b.png",
    alternatives: [],
    created_at: "2025-01-25",
  },
  {
    id: "8",
    medicine_name: "Fexo 120",
    generic_name: "Fexofenadine",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Allergy",
    type: "Tablet",
    description: "Fexo 120 is a non-sedating antihistamine used for the relief of symptoms associated with seasonal allergic rhinitis and chronic urticaria.",
    usage: "Relief of sneezing, runny nose, itchy/watery eyes associated with hay fever and seasonal allergies. Also for chronic idiopathic urticaria.",
    dosage: {
      adult: "120mg once daily or 60mg twice daily.",
      child: "30mg twice daily for children 6-11 years.",
      elderly: "Standard adult dose.",
      special_instructions: "Take with water. Avoid fruit juices within 4 hours.",
    },
    side_effects: {
      common: ["Headache", "Drowsiness (rare)", "Nausea"],
      serious: ["Hypersensitivity reactions (very rare)"],
    },
    precautions: {
      pregnancy: "Category C. Use only if benefit outweighs risk.",
      kidney: "Reduce dose in severe renal impairment.",
      liver: "Safe in mild hepatic impairment.",
      allergy: "Avoid if allergic to fexofenadine or terfenadine.",
      drug_interaction: "Avoid with erythromycin and ketoconazole.",
    },
    who_should_avoid: ["Patients allergic to fexofenadine", "Severe renal impairment without dose adjustment"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 8.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-19" },
    image: "/medicines/fexo.png",
    alternatives: [],
    created_at: "2025-03-01",
  },
  {
    id: "9",
    medicine_name: "Insulet N",
    generic_name: "Insulin (Human) Isophane",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Diabetes",
    type: "Injection",
    description: "Insulet N is an intermediate-acting insulin used for the management of diabetes mellitus to control blood glucose levels.",
    usage: "Management of Type 1 and Type 2 diabetes mellitus. Controls blood sugar levels throughout the day.",
    dosage: {
      adult: "Individualized based on blood glucose monitoring. Usually 0.5-1 unit/kg/day.",
      child: "Individualized. Usually 0.5-0.8 units/kg/day.",
      elderly: "Start with lower doses. Monitor closely.",
      special_instructions: "Inject subcutaneously. Rotate injection sites. Do not inject intravenously.",
    },
    side_effects: {
      common: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
      serious: ["Severe hypoglycemia", "Allergic reactions", "Lipodystrophy"],
    },
    precautions: {
      pregnancy: "Category B. Essential for diabetic pregnancy management.",
      kidney: "Dose reduction may be needed in renal impairment.",
      liver: "Dose reduction may be needed in hepatic impairment.",
      allergy: "Avoid if allergic to insulin or any excipient.",
      drug_interaction: "Beta-blockers may mask hypoglycemia symptoms.",
    },
    who_should_avoid: ["Those with insulin allergy", "During hypoglycemic episodes"],
    storage: ["Refrigerate at 2-8°C", "Do not freeze", "In-use vials can be stored at room temperature for 28 days"],
    price: { unit_price: 420.0, strip_price: 420, currency: "BDT", updated_date: "2025-05-17" },
    image: "/medicines/insulet.png",
    alternatives: [],
    created_at: "2025-02-15",
  },
  {
    id: "10",
    medicine_name: "Cardipro 5",
    generic_name: "Amlodipine",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Heart Care",
    type: "Tablet",
    description: "Cardipro is a calcium channel blocker used for the treatment of hypertension and angina pectoris.",
    usage: "Treatment of high blood pressure and chest pain (angina). May be used alone or in combination with other antihypertensives.",
    dosage: {
      adult: "5mg once daily initially. Maximum 10mg/day.",
      child: "2.5-5mg once daily for children 6-17 years.",
      elderly: "Start with 2.5mg daily.",
      special_instructions: "Take at the same time each day. Do not stop suddenly.",
    },
    side_effects: {
      common: ["Edema", "Fatigue", "Dizziness", "Flushing", "Palpitations"],
      serious: ["Severe hypotension", "Myocardial infarction (rare)", "Hepatitis"],
    },
    precautions: {
      pregnancy: "Category C. Use only if clearly needed.",
      kidney: "No dose adjustment needed.",
      liver: "Start with 2.5mg in hepatic impairment.",
      allergy: "Avoid if allergic to amlodipine or dihydropyridines.",
      drug_interaction: "May interact with simvastatin, cyclosporine, and CYP3A4 inhibitors.",
    },
    who_should_avoid: ["Severe aortic stenosis patients", "Those with cardiogenic shock"],
    storage: ["Store below 30°C", "Protect from light and moisture"],
    price: { unit_price: 4.0, strip_price: 120, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/cardipro.png",
    alternatives: [],
    created_at: "2025-03-10",
  },
  {
    id: "11",
    medicine_name: "Dermovate",
    generic_name: "Clobetasol Propionate",
    company_name: "Opsonin Pharma",
    company_id: "5",
    category: "Skin Care",
    type: "Cream",
    description: "Dermovate is a very potent topical corticosteroid used for the treatment of severe inflammatory skin conditions.",
    usage: "Treatment of eczema, psoriasis, dermatitis, and other severe inflammatory skin conditions unresponsive to less potent corticosteroids.",
    dosage: {
      adult: "Apply a thin layer to affected area twice daily for up to 2 weeks.",
      child: "Not recommended for children under 1 year. Use minimally in older children.",
      elderly: "Use with caution. Skin may be more susceptible to side effects.",
      special_instructions: "Do not apply to face, groin, or axillae. Do not use under occlusive dressings.",
    },
    side_effects: {
      common: ["Burning sensation", "Skin thinning", "Stretch marks", "Itching"],
      serious: ["Adrenal suppression", "Cushing syndrome", "Skin atrophy", "Secondary infection"],
    },
    precautions: {
      pregnancy: "Avoid during pregnancy unless essential.",
      kidney: "Systemic absorption possible with extensive use.",
      liver: "Use with caution.",
      allergy: "Avoid if allergic to clobetasol or other corticosteroids.",
      drug_interaction: "Minimal systemic interactions with topical use.",
    },
    who_should_avoid: ["Patients with rosacea", "Acne patients", "Fungal skin infections", "Viral skin infections"],
    storage: ["Store below 25°C", "Do not freeze"],
    price: { unit_price: 65.0, strip_price: 65, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/dermovate.png",
    alternatives: [],
    created_at: "2025-03-15",
  },
  {
    id: "12",
    medicine_name: "Pedeamin",
    generic_name: "Multivitamin Drops",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Children Care",
    type: "Drops",
    description: "Pedeamin is a pediatric multivitamin supplement providing essential vitamins for growing children.",
    usage: "Prevention and treatment of vitamin deficiency in infants and children. Supports healthy growth and development.",
    dosage: {
      adult: "Not intended for adult use.",
      child: "0.3-0.6ml daily for infants. 0.6-1ml daily for children 1-3 years.",
      elderly: "Not applicable.",
      special_instructions: "Use the dropper provided. Can be mixed with food or juice.",
    },
    side_effects: {
      common: ["Mild stomach upset", "Temporary staining of teeth"],
      serious: ["Allergic reactions (very rare)", "Vitamin toxicity with overdose"],
    },
    precautions: {
      pregnancy: "Not applicable - pediatric product.",
      kidney: "Safe in recommended doses.",
      liver: "Safe in recommended doses.",
      allergy: "Check for allergy to any vitamin component.",
      drug_interaction: "May interact with certain antibiotics if contains iron.",
    },
    who_should_avoid: ["Children allergic to any component", "Hypervitaminosis"],
    storage: ["Store below 25°C", "Protect from light", "Use within 30 days of opening"],
    price: { unit_price: 80.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/pedeamin.png",
    alternatives: [],
    created_at: "2025-04-01",
  },
];

export const companies: Company[] = [
  {
    id: "1",
    name: "Square Pharmaceuticals",
    logo: "/companies/square.png",
    about: "Square Pharmaceuticals Ltd. is the largest pharmaceutical company in Bangladesh. Established in 1958, it has been serving the nation with quality medicines for over 6 decades. The company manufactures and markets a wide range of pharmaceutical products.",
    total_medicines: 850,
    categories: ["Antibiotics", "Pain Relief", "Gastric", "Vitamins", "Heart Care", "Diabetes"],
    popular_products: ["Ace Plus", "Sergel 20", "Zimax 500", "Neuro-B"],
    founded: "1958",
    headquarters: "Pabna, Bangladesh",
  },
  {
    id: "2",
    name: "Beximco Pharmaceuticals",
    logo: "/companies/beximco.png",
    about: "Beximco Pharmaceuticals Ltd. is one of the leading pharmaceutical companies in Bangladesh, known for manufacturing high-quality medicines at affordable prices. Listed on both Dhaka and London Stock Exchanges.",
    total_medicines: 620,
    categories: ["Pain Relief", "Antibiotics", "Vitamins", "Skin Care", "Gastric"],
    popular_products: ["Napa Extra", "Napa", "Neofloxin", "Dexoren"],
    founded: "1976",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "3",
    name: "Incepta Pharmaceuticals",
    logo: "/companies/incepta.png",
    about: "Incepta Pharmaceuticals Ltd. is one of the fastest-growing pharmaceutical companies in Bangladesh. Known for innovation and quality, Incepta manufactures a wide range of dosage forms including tablets, capsules, injectables, and more.",
    total_medicines: 750,
    categories: ["Antibiotics", "Diabetes", "Heart Care", "Gastric", "Allergy"],
    popular_products: ["Azicin 500", "Losectil 20", "Insulet N"],
    founded: "1999",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "4",
    name: "Renata Limited",
    logo: "/companies/renata.png",
    about: "Renata Limited is a leading Bangladeshi pharmaceutical company committed to improving healthcare through innovative medicines and animal health products. Known for strict quality standards and ethical practices.",
    total_medicines: 480,
    categories: ["Heart Care", "Allergy", "Antibiotics", "Pain Relief", "Vitamins"],
    popular_products: ["Fexo 120", "Cardipro 5"],
    founded: "1972",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "5",
    name: "Opsonin Pharma",
    logo: "/companies/opsonin.png",
    about: "Opsonin Pharma Limited is a prominent pharmaceutical manufacturer in Bangladesh, producing a diverse portfolio of medicines. The company is known for its commitment to quality and affordable healthcare.",
    total_medicines: 380,
    categories: ["Skin Care", "Pain Relief", "Antibiotics", "Gastric"],
    popular_products: ["Dermovate"],
    founded: "1956",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "6",
    name: "Healthcare Pharmaceuticals",
    logo: "/companies/healthcare.png",
    about: "Healthcare Pharmaceuticals Ltd. specializes in producing quality pharmaceutical products with a focus on pediatric care and specialized medicines for the Bangladesh market.",
    total_medicines: 320,
    categories: ["Children Care", "Vitamins", "Pain Relief", "Fever"],
    popular_products: ["Pedeamin"],
    founded: "1986",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "7",
    name: "ACI Limited",
    logo: "/companies/aci.png",
    about: "ACI Limited is a diversified conglomerate with a strong presence in the pharmaceutical sector. ACI Pharma produces a wide range of quality medicines serving millions of patients across Bangladesh.",
    total_medicines: 350,
    categories: ["Antibiotics", "Pain Relief", "Heart Care", "Diabetes", "Vitamins"],
    popular_products: ["ACI Paracetamol", "ACI Omeprazole"],
    founded: "1968",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "8",
    name: "Eskayef Pharmaceuticals",
    logo: "/companies/eskayef.png",
    about: "Eskayef Pharmaceuticals Ltd. is a leading pharmaceutical company in Bangladesh, known for producing world-class quality medicines. A subsidiary of Transcom Group, Eskayef has earned trust through decades of service.",
    total_medicines: 420,
    categories: ["Antibiotics", "Gastric", "Heart Care", "Pain Relief", "Allergy"],
    popular_products: ["Esoral", "Atova"],
    founded: "1940",
    headquarters: "Dhaka, Bangladesh",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "understanding-antibiotic-resistance",
    title: "Understanding Antibiotic Resistance: A Growing Concern",
    excerpt: "Learn about the growing threat of antibiotic resistance and how to use antibiotics responsibly to protect public health.",
    content: `Antibiotic resistance is one of the biggest threats to global health, food security, and development. It occurs when bacteria change in response to the use of antibiotic medicines.\n\nAntibiotic resistance happens naturally, but misuse of antibiotics in humans and animals is accelerating the process. A growing number of infections are becoming harder to treat as the antibiotics used to treat them become less effective.\n\n## What Causes Antibiotic Resistance?\n\n1. **Overuse of antibiotics** - Taking antibiotics when they're not needed\n2. **Not completing the full course** - Stopping treatment early\n3. **Self-medication** - Using leftover antibiotics without prescription\n4. **Use in agriculture** - Excessive use in livestock farming\n\n## How to Prevent Antibiotic Resistance\n\n- Only use antibiotics when prescribed by a doctor\n- Always complete the full prescription\n- Never share antibiotics with others\n- Prevent infections through good hygiene\n- Keep vaccinations up to date\n\nBy being responsible with antibiotic use, we can help slow down resistance and ensure these life-saving medicines remain effective for future generations.`,
    category: "Drug Awareness",
    image: "/blog/antibiotic-resistance.jpg",
    author: "Dr. Rahman",
    date: "2025-05-15",
    read_time: "5 min read",
  },
  {
    id: "2",
    slug: "managing-diabetes-with-lifestyle",
    title: "Managing Diabetes Through Lifestyle Changes",
    excerpt: "Discover how diet, exercise, and lifestyle modifications can significantly impact diabetes management alongside medication.",
    content: `Diabetes management is more than just taking medication. Lifestyle changes play a crucial role in controlling blood sugar levels and preventing complications.\n\n## Diet Management\n\n- Choose complex carbohydrates over simple sugars\n- Include plenty of fiber in your diet\n- Control portion sizes\n- Eat at regular intervals\n\n## Exercise Benefits\n\nRegular physical activity helps your body use insulin more effectively. Aim for at least 150 minutes of moderate exercise per week.\n\n## Stress Management\n\nStress hormones can raise blood sugar levels. Practice relaxation techniques like deep breathing, meditation, or yoga.\n\n## Regular Monitoring\n\nKeep track of your blood sugar levels and maintain regular check-ups with your healthcare provider. This helps in early detection of any complications.`,
    category: "Health Tips",
    image: "/blog/diabetes-lifestyle.jpg",
    author: "Dr. Karim",
    date: "2025-05-10",
    read_time: "7 min read",
  },
  {
    id: "3",
    slug: "medicine-storage-guide",
    title: "How to Store Medicines Safely at Home",
    excerpt: "A comprehensive guide on proper medicine storage to ensure safety and maintain medication effectiveness.",
    content: `Proper storage of medicines is essential for maintaining their effectiveness and ensuring safety.\n\n## General Storage Tips\n\n1. **Cool, dry place** - Most medicines should be stored below 25°C\n2. **Away from sunlight** - UV light can degrade medications\n3. **Out of reach of children** - Use child-proof containers\n4. **Original packaging** - Keep medicines in their original containers\n\n## Refrigerated Medicines\n\nSome medicines like insulin need refrigeration (2-8°C). Never freeze unless specified.\n\n## Medicine Cabinet Organization\n\n- Check expiry dates regularly\n- Dispose of expired medicines properly\n- Keep a list of all medications\n- Separate adult and children's medicines\n\n## What NOT to Do\n\n- Don't store medicines in the bathroom (humidity)\n- Don't transfer medicines to different containers\n- Don't keep medicines in direct sunlight\n- Don't store medicines near heat sources`,
    category: "Medicine Safety",
    image: "/blog/medicine-storage.jpg",
    author: "Pharmacist Hasan",
    date: "2025-05-05",
    read_time: "4 min read",
  },
  {
    id: "4",
    slug: "importance-of-generic-medicines",
    title: "Generic Medicines: Same Quality, Lower Cost",
    excerpt: "Understanding why generic medicines are equally effective as brand-name drugs and how they can save you money.",
    content: `Generic medicines contain the same active ingredients as their brand-name counterparts and are equally safe and effective.\n\n## What Makes Generics the Same?\n\n- **Same active ingredient** - Identical chemical composition\n- **Same dosage** - Equal strength and form\n- **Same quality standards** - Must meet regulatory requirements\n- **Bioequivalent** - Absorbed at the same rate\n\n## Why Are They Cheaper?\n\nGeneric manufacturers don't have the cost of drug discovery and clinical trials, allowing them to offer the same medicine at significantly lower prices.\n\n## Bangladesh's Generic Medicine Industry\n\nBangladesh has a thriving generic pharmaceutical industry that provides affordable medicines to millions. The industry is recognized globally for quality manufacturing.`,
    category: "Healthcare Education",
    image: "/blog/generic-medicines.jpg",
    author: "Dr. Sultana",
    date: "2025-04-28",
    read_time: "6 min read",
  },
  {
    id: "5",
    slug: "common-drug-interactions",
    title: "Common Drug Interactions You Should Know About",
    excerpt: "Learn about dangerous drug interactions and how to safely manage multiple medications.",
    content: `Drug interactions can change how your medications work or increase the risk of serious side effects.\n\n## Types of Interactions\n\n### Drug-Drug Interactions\nWhen two or more drugs react with each other. Example: Blood thinners with aspirin.\n\n### Drug-Food Interactions\nSome foods can affect how drugs work. Example: Grapefruit with statins.\n\n### Drug-Condition Interactions\nCertain medical conditions can make some drugs harmful. Example: Aspirin in patients with bleeding disorders.\n\n## How to Prevent Interactions\n\n1. Tell your doctor about all medications you take\n2. Use one pharmacy for all prescriptions\n3. Read medication labels carefully\n4. Ask about potential interactions before starting new medicines\n5. Never mix medications without medical advice`,
    category: "Drug Awareness",
    image: "/blog/drug-interactions.jpg",
    author: "Dr. Ahmed",
    date: "2025-04-20",
    read_time: "5 min read",
  },
  {
    id: "6",
    slug: "pediatric-medicine-safety",
    title: "Giving Medicine to Children: A Parent's Guide",
    excerpt: "Essential tips for safely administering medicine to children, including dosage calculation and common mistakes to avoid.",
    content: `Giving medicine to children requires extra care and attention. Here's what every parent should know.\n\n## Dosage Guidelines\n\n- Always use the measuring device provided\n- Never use household spoons for liquid medicines\n- Follow weight-based dosing, not age-based\n- Never give adult medicines to children\n\n## Common Mistakes\n\n1. **Wrong dosage** - Always double-check measurements\n2. **Wrong timing** - Maintain consistent intervals\n3. **Stopping early** - Complete the full course\n4. **Self-prescribing** - Always consult a pediatrician\n\n## Making Medicine Time Easier\n\n- Use flavored medicines when available\n- Mix liquid medicines with a small amount of food\n- Praise children after taking medicine\n- Explain why the medicine is important in simple terms`,
    category: "Health Tips",
    image: "/blog/pediatric-safety.jpg",
    author: "Dr. Fatima",
    date: "2025-04-15",
    read_time: "6 min read",
  },
];

export function searchMedicines(query: string): Medicine[] {
  const q = query.toLowerCase().trim();
  if (!q) return medicines;
  return medicines.filter(
    (m) =>
      m.medicine_name.toLowerCase().includes(q) ||
      m.generic_name.toLowerCase().includes(q) ||
      m.company_name.toLowerCase().includes(q) ||
      m.category.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.type.toLowerCase().includes(q)
  );
}

export function getMedicineById(id: string): Medicine | undefined {
  return medicines.find((m) => m.id === id);
}

export function getCompanyById(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}

export function getMedicinesByCompany(companyId: string): Medicine[] {
  return medicines.filter((m) => m.company_id === companyId);
}

export function getMedicinesByCategory(category: string): Medicine[] {
  return medicines.filter((m) => m.category.toLowerCase() === category.toLowerCase());
}

export function getBlogBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((b) => b.slug === slug);
}

export function getAlternativeMedicines(medicine: Medicine): Medicine[] {
  return medicine.alternatives
    .map((id) => medicines.find((m) => m.id === id))
    .filter((m): m is Medicine => m !== undefined);
}

export const trendingSearches = [
  "Napa Extra",
  "Sergel",
  "Azithromycin",
  "Omeprazole",
  "Paracetamol",
  "Fexofenadine",
  "Vitamin B",
  "Insulin",
];
