import { Medicine, Company, BlogPost, Category } from "./types";

export const categories: Category[] = [
  { id: "1", name: "Antibiotics", icon: "Shield", description: "Fight bacterial infections", count: 245 },
  { id: "2", name: "Pain Relief", icon: "Zap", description: "Manage pain effectively", count: 189 },
  { id: "3", name: "Diabetes", icon: "Activity", description: "Control blood sugar levels", count: 156 },
  { id: "4", name: "Heart Care", icon: "Heart", description: "Cardiovascular health", count: 134 },
  { id: "5", name: "Vitamins", icon: "Sun", description: "Essential supplements", count: 210 },
  { id: "6", name: "Skin Care", icon: "Sparkles", description: "Dermatological treatments", count: 178 },
  { id: "7", name: "Gastric", icon: "CircleDot", description: "Digestive health solutions", count: 145 },
  { id: "8", name: "Allergy", icon: "Wind", description: "Allergy relief medicines", count: 98 },
  { id: "9", name: "Fever", icon: "Thermometer", description: "Temperature management", count: 167 },
  { id: "10", name: "Children Care", icon: "Baby", description: "Pediatric medicines", count: 123 },
];

export const medicines: Medicine[] = [
  {
    id: "1",
    medicine_name: "Napa Extra",
    generic_name: "Paracetamol + Caffeine",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Pain Relief",
    type: "Tablet",
    description: "Napa Extra is a combination of Paracetamol and Caffeine used for the relief of mild to moderate pain including headache, migraine, toothache, period pain, and cold & flu symptoms.",
    usage: "Used for temporary relief of mild to moderate pain and fever. Effective for headache, muscle ache, backache, toothache, menstrual cramps, and arthritis pain.",
    dosage: {
      adult: "1-2 tablets every 4-6 hours as needed. Maximum 8 tablets in 24 hours.",
      child: "Not recommended for children under 12 years without medical advice.",
      elderly: "1 tablet every 6-8 hours. Maximum 4 tablets in 24 hours.",
      special_instructions: "Take with a full glass of water. Can be taken with or without food.",
    },
    side_effects: {
      common: ["Nausea", "Stomach upset", "Dizziness", "Insomnia (due to caffeine)"],
      serious: ["Allergic reaction", "Liver damage (with overdose)", "Severe skin reaction", "Blood disorders"],
    },
    precautions: {
      pregnancy: "Consult doctor before use during pregnancy. Category B drug.",
      kidney: "Use with caution in patients with kidney impairment. Dose adjustment may be needed.",
      liver: "Avoid in severe liver disease. Maximum 2g/day in liver impairment.",
      allergy: "Do not use if allergic to paracetamol or caffeine.",
      drug_interaction: "May interact with warfarin, metoclopramide, and cholestyramine.",
    },
    who_should_avoid: [
      "Patients with severe liver disease",
      "Those allergic to paracetamol or caffeine",
      "Chronic alcohol users",
      "Patients taking other paracetamol-containing products",
    ],
    storage: ["Store below 25°C", "Keep away from sunlight", "Keep away from children", "Store in dry place"],
    price: { unit_price: 2.5, strip_price: 25, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/napa-extra.png",
    alternatives: ["2", "3"],
    created_at: "2025-01-15",
  },
  {
    id: "2",
    medicine_name: "Ace Plus",
    generic_name: "Paracetamol + Caffeine",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Pain Relief",
    type: "Tablet",
    description: "Ace Plus provides effective relief from pain and fever with the combination of Paracetamol and Caffeine for enhanced analgesic effect.",
    usage: "Indicated for temporary relief of mild to moderate pain associated with headache, cold, toothache, muscular aches, menstrual periods, and minor arthritis pain.",
    dosage: {
      adult: "1-2 tablets every 4-6 hours. Maximum 8 tablets per day.",
      child: "Not recommended below 12 years.",
      elderly: "Reduced dose recommended. 1 tablet every 6 hours.",
      special_instructions: "Do not exceed recommended dose. Take with water.",
    },
    side_effects: {
      common: ["Nausea", "Vomiting", "Constipation"],
      serious: ["Hepatotoxicity", "Thrombocytopenia", "Anaphylaxis"],
    },
    precautions: {
      pregnancy: "Use only if clearly needed. Consult physician.",
      kidney: "Caution in renal impairment.",
      liver: "Contraindicated in severe hepatic impairment.",
      allergy: "Avoid if hypersensitive to any component.",
      drug_interaction: "Caution with anticoagulants and hepatotoxic drugs.",
    },
    who_should_avoid: ["Severe liver disease patients", "Known hypersensitivity"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/ace-plus.png",
    alternatives: ["1", "3"],
    created_at: "2025-01-10",
  },
  {
    id: "3",
    medicine_name: "Sergel 20",
    generic_name: "Omeprazole",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Gastric",
    type: "Capsule",
    description: "Sergel 20 is a proton pump inhibitor used to treat gastroesophageal reflux disease (GERD), gastric ulcers, and other acid-related disorders.",
    usage: "Treatment of duodenal ulcer, gastric ulcer, reflux esophagitis, and Zollinger-Ellison syndrome. Also used for H. pylori eradication in combination therapy.",
    dosage: {
      adult: "20mg once daily before breakfast for 2-8 weeks.",
      child: "10-20mg once daily based on weight. Consult pediatrician.",
      elderly: "No dose adjustment required.",
      special_instructions: "Take 30 minutes before meals. Swallow whole, do not crush or chew.",
    },
    side_effects: {
      common: ["Headache", "Diarrhea", "Nausea", "Abdominal pain", "Flatulence"],
      serious: ["C. difficile infection", "Bone fractures with long-term use", "Hypomagnesemia", "Vitamin B12 deficiency"],
    },
    precautions: {
      pregnancy: "Category C. Use only if potential benefit justifies risk.",
      kidney: "No dose adjustment in mild-moderate impairment.",
      liver: "Maximum 20mg/day in severe hepatic impairment.",
      allergy: "Avoid if allergic to proton pump inhibitors.",
      drug_interaction: "May interact with clopidogrel, methotrexate, and ketoconazole.",
    },
    who_should_avoid: ["Patients with known PPI allergy", "Those taking rilpivirine"],
    storage: ["Store below 25°C", "Protect from light and moisture", "Keep away from children"],
    price: { unit_price: 6.0, strip_price: 84, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/sergel.png",
    alternatives: ["7"],
    created_at: "2025-02-01",
  },
  {
    id: "4",
    medicine_name: "Zimax 500",
    generic_name: "Azithromycin",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Antibiotics",
    type: "Tablet",
    description: "Zimax 500 is a broad-spectrum macrolide antibiotic used to treat various bacterial infections including respiratory tract, skin, and soft tissue infections.",
    usage: "Treatment of upper and lower respiratory tract infections, skin and soft tissue infections, otitis media, and sexually transmitted diseases.",
    dosage: {
      adult: "500mg once daily for 3 days, or 500mg on day 1 followed by 250mg on days 2-5.",
      child: "10mg/kg once daily for 3 days. Maximum 500mg/day.",
      elderly: "No dose adjustment required with normal renal function.",
      special_instructions: "Take 1 hour before or 2 hours after meals. Complete the full course.",
    },
    side_effects: {
      common: ["Diarrhea", "Nausea", "Abdominal pain", "Vomiting"],
      serious: ["QT prolongation", "Hepatotoxicity", "Clostridium difficile colitis", "Severe allergic reactions"],
    },
    precautions: {
      pregnancy: "Category B. Use only if clearly needed.",
      kidney: "Caution in severe renal impairment.",
      liver: "Avoid in severe hepatic disease.",
      allergy: "Contraindicated in macrolide allergy.",
      drug_interaction: "May interact with antacids, warfarin, and digoxin.",
    },
    who_should_avoid: ["Patients allergic to macrolides", "Severe liver disease", "History of QT prolongation"],
    storage: ["Store below 30°C", "Keep in original packaging", "Away from children"],
    price: { unit_price: 30.0, strip_price: 90, currency: "BDT", updated_date: "2025-05-10" },
    image: "/medicines/zimax.png",
    alternatives: ["5"],
    created_at: "2025-01-20",
  },
  {
    id: "5",
    medicine_name: "Azicin 500",
    generic_name: "Azithromycin",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Antibiotics",
    type: "Tablet",
    description: "Azicin is a macrolide antibiotic effective against a wide range of gram-positive and gram-negative bacteria.",
    usage: "Used for treating bacterial infections of the respiratory tract, ear, skin, and urogenital tract.",
    dosage: {
      adult: "500mg once daily for 3 days.",
      child: "10mg/kg/day for 3 days.",
      elderly: "Standard adult dose with normal organ function.",
      special_instructions: "Take on empty stomach for best absorption.",
    },
    side_effects: {
      common: ["Diarrhea", "Nausea", "Abdominal cramps"],
      serious: ["Liver dysfunction", "Cardiac arrhythmias", "Angioedema"],
    },
    precautions: {
      pregnancy: "Consult doctor. Category B.",
      kidney: "Use with caution.",
      liver: "Monitor liver function.",
      allergy: "Avoid in macrolide hypersensitivity.",
      drug_interaction: "Avoid with ergot alkaloids.",
    },
    who_should_avoid: ["Macrolide-allergic patients", "Severe hepatic impairment"],
    storage: ["Store below 30°C", "Protect from moisture"],
    price: { unit_price: 25.0, strip_price: 75, currency: "BDT", updated_date: "2025-05-12" },
    image: "/medicines/azicin.png",
    alternatives: ["4"],
    created_at: "2025-02-05",
  },
  {
    id: "6",
    medicine_name: "Losectil 20",
    generic_name: "Omeprazole",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Gastric",
    type: "Capsule",
    description: "Losectil is a proton pump inhibitor that reduces gastric acid secretion for the treatment of acid-related gastrointestinal disorders.",
    usage: "Treatment of peptic ulcers, GERD, and acid hypersecretory conditions.",
    dosage: {
      adult: "20mg once daily for 4-8 weeks.",
      child: "Based on body weight. Consult pediatrician.",
      elderly: "Standard dose. No adjustment needed.",
      special_instructions: "Take before breakfast. Do not crush capsules.",
    },
    side_effects: {
      common: ["Headache", "Nausea", "Diarrhea", "Constipation"],
      serious: ["Interstitial nephritis", "Bone fractures", "Hypomagnesemia"],
    },
    precautions: {
      pregnancy: "Use only when clearly needed.",
      kidney: "No dose adjustment for mild impairment.",
      liver: "Reduce dose in severe hepatic impairment.",
      allergy: "Avoid in PPI allergy.",
      drug_interaction: "Interacts with clopidogrel and phenytoin.",
    },
    who_should_avoid: ["PPI-allergic patients"],
    storage: ["Store below 25°C", "Protect from light"],
    price: { unit_price: 5.0, strip_price: 70, currency: "BDT", updated_date: "2025-05-14" },
    image: "/medicines/losectil.png",
    alternatives: ["3"],
    created_at: "2025-02-10",
  },
  {
    id: "7",
    medicine_name: "Neuro-B",
    generic_name: "Vitamin B1 + B6 + B12",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Vitamins",
    type: "Tablet",
    description: "Neuro-B is a combination of essential B vitamins that supports nerve health and helps prevent vitamin B deficiency.",
    usage: "Prevention and treatment of Vitamin B deficiency. Supports nerve function, energy metabolism, and red blood cell formation.",
    dosage: {
      adult: "1-2 tablets daily after meals.",
      child: "As directed by physician.",
      elderly: "1 tablet daily.",
      special_instructions: "Take with food for better absorption.",
    },
    side_effects: {
      common: ["Mild stomach upset", "Nausea"],
      serious: ["Allergic reactions (rare)", "Peripheral neuropathy with excessive B6"],
    },
    precautions: {
      pregnancy: "Generally safe. Consult doctor for appropriate dose.",
      kidney: "Safe in normal doses.",
      liver: "Safe in normal doses.",
      allergy: "Avoid if allergic to any B vitamin.",
      drug_interaction: "May interact with levodopa and phenytoin.",
    },
    who_should_avoid: ["Those allergic to B vitamins"],
    storage: ["Store below 30°C", "Protect from light and moisture"],
    price: { unit_price: 3.5, strip_price: 105, currency: "BDT", updated_date: "2025-05-16" },
    image: "/medicines/neuro-b.png",
    alternatives: [],
    created_at: "2025-01-25",
  },
  {
    id: "8",
    medicine_name: "Fexo 120",
    generic_name: "Fexofenadine",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Allergy",
    type: "Tablet",
    description: "Fexo 120 is a non-sedating antihistamine used for the relief of symptoms associated with seasonal allergic rhinitis and chronic urticaria.",
    usage: "Relief of sneezing, runny nose, itchy/watery eyes associated with hay fever and seasonal allergies. Also for chronic idiopathic urticaria.",
    dosage: {
      adult: "120mg once daily or 60mg twice daily.",
      child: "30mg twice daily for children 6-11 years.",
      elderly: "Standard adult dose.",
      special_instructions: "Take with water. Avoid fruit juices within 4 hours.",
    },
    side_effects: {
      common: ["Headache", "Drowsiness (rare)", "Nausea"],
      serious: ["Hypersensitivity reactions (very rare)"],
    },
    precautions: {
      pregnancy: "Category C. Use only if benefit outweighs risk.",
      kidney: "Reduce dose in severe renal impairment.",
      liver: "Safe in mild hepatic impairment.",
      allergy: "Avoid if allergic to fexofenadine or terfenadine.",
      drug_interaction: "Avoid with erythromycin and ketoconazole.",
    },
    who_should_avoid: ["Patients allergic to fexofenadine", "Severe renal impairment without dose adjustment"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 8.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-19" },
    image: "/medicines/fexo.png",
    alternatives: [],
    created_at: "2025-03-01",
  },
  {
    id: "9",
    medicine_name: "Insulet N",
    generic_name: "Insulin (Human) Isophane",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Diabetes",
    type: "Injection",
    description: "Insulet N is an intermediate-acting insulin used for the management of diabetes mellitus to control blood glucose levels.",
    usage: "Management of Type 1 and Type 2 diabetes mellitus. Controls blood sugar levels throughout the day.",
    dosage: {
      adult: "Individualized based on blood glucose monitoring. Usually 0.5-1 unit/kg/day.",
      child: "Individualized. Usually 0.5-0.8 units/kg/day.",
      elderly: "Start with lower doses. Monitor closely.",
      special_instructions: "Inject subcutaneously. Rotate injection sites. Do not inject intravenously.",
    },
    side_effects: {
      common: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
      serious: ["Severe hypoglycemia", "Allergic reactions", "Lipodystrophy"],
    },
    precautions: {
      pregnancy: "Category B. Essential for diabetic pregnancy management.",
      kidney: "Dose reduction may be needed in renal impairment.",
      liver: "Dose reduction may be needed in hepatic impairment.",
      allergy: "Avoid if allergic to insulin or any excipient.",
      drug_interaction: "Beta-blockers may mask hypoglycemia symptoms.",
    },
    who_should_avoid: ["Those with insulin allergy", "During hypoglycemic episodes"],
    storage: ["Refrigerate at 2-8°C", "Do not freeze", "In-use vials can be stored at room temperature for 28 days"],
    price: { unit_price: 420.0, strip_price: 420, currency: "BDT", updated_date: "2025-05-17" },
    image: "/medicines/insulet.png",
    alternatives: [],
    created_at: "2025-02-15",
  },
  {
    id: "10",
    medicine_name: "Cardipro 5",
    generic_name: "Amlodipine",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Heart Care",
    type: "Tablet",
    description: "Cardipro is a calcium channel blocker used for the treatment of hypertension and angina pectoris.",
    usage: "Treatment of high blood pressure and chest pain (angina). May be used alone or in combination with other antihypertensives.",
    dosage: {
      adult: "5mg once daily initially. Maximum 10mg/day.",
      child: "2.5-5mg once daily for children 6-17 years.",
      elderly: "Start with 2.5mg daily.",
      special_instructions: "Take at the same time each day. Do not stop suddenly.",
    },
    side_effects: {
      common: ["Edema", "Fatigue", "Dizziness", "Flushing", "Palpitations"],
      serious: ["Severe hypotension", "Myocardial infarction (rare)", "Hepatitis"],
    },
    precautions: {
      pregnancy: "Category C. Use only if clearly needed.",
      kidney: "No dose adjustment needed.",
      liver: "Start with 2.5mg in hepatic impairment.",
      allergy: "Avoid if allergic to amlodipine or dihydropyridines.",
      drug_interaction: "May interact with simvastatin, cyclosporine, and CYP3A4 inhibitors.",
    },
    who_should_avoid: ["Severe aortic stenosis patients", "Those with cardiogenic shock"],
    storage: ["Store below 30°C", "Protect from light and moisture"],
    price: { unit_price: 4.0, strip_price: 120, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/cardipro.png",
    alternatives: [],
    created_at: "2025-03-10",
  },
  {
    id: "11",
    medicine_name: "Dermovate",
    generic_name: "Clobetasol Propionate",
    company_name: "Opsonin Pharma",
    company_id: "5",
    category: "Skin Care",
    type: "Cream",
    description: "Dermovate is a very potent topical corticosteroid used for the treatment of severe inflammatory skin conditions.",
    usage: "Treatment of eczema, psoriasis, dermatitis, and other severe inflammatory skin conditions unresponsive to less potent corticosteroids.",
    dosage: {
      adult: "Apply a thin layer to affected area twice daily for up to 2 weeks.",
      child: "Not recommended for children under 1 year. Use minimally in older children.",
      elderly: "Use with caution. Skin may be more susceptible to side effects.",
      special_instructions: "Do not apply to face, groin, or axillae. Do not use under occlusive dressings.",
    },
    side_effects: {
      common: ["Burning sensation", "Skin thinning", "Stretch marks", "Itching"],
      serious: ["Adrenal suppression", "Cushing syndrome", "Skin atrophy", "Secondary infection"],
    },
    precautions: {
      pregnancy: "Avoid during pregnancy unless essential.",
      kidney: "Systemic absorption possible with extensive use.",
      liver: "Use with caution.",
      allergy: "Avoid if allergic to clobetasol or other corticosteroids.",
      drug_interaction: "Minimal systemic interactions with topical use.",
    },
    who_should_avoid: ["Patients with rosacea", "Acne patients", "Fungal skin infections", "Viral skin infections"],
    storage: ["Store below 25°C", "Do not freeze"],
    price: { unit_price: 65.0, strip_price: 65, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/dermovate.png",
    alternatives: [],
    created_at: "2025-03-15",
  },
  {
    id: "12",
    medicine_name: "Pedeamin",
    generic_name: "Multivitamin Drops",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Children Care",
    type: "Drops",
    description: "Pedeamin is a pediatric multivitamin supplement providing essential vitamins for growing children.",
    usage: "Prevention and treatment of vitamin deficiency in infants and children. Supports healthy growth and development.",
    dosage: {
      adult: "Not intended for adult use.",
      child: "0.3-0.6ml daily for infants. 0.6-1ml daily for children 1-3 years.",
      elderly: "Not applicable.",
      special_instructions: "Use the dropper provided. Can be mixed with food or juice.",
    },
    side_effects: {
      common: ["Mild stomach upset", "Temporary staining of teeth"],
      serious: ["Allergic reactions (very rare)", "Vitamin toxicity with overdose"],
    },
    precautions: {
      pregnancy: "Not applicable - pediatric product.",
      kidney: "Safe in recommended doses.",
      liver: "Safe in recommended doses.",
      allergy: "Check for allergy to any vitamin component.",
      drug_interaction: "May interact with certain antibiotics if contains iron.",
    },
    who_should_avoid: ["Children allergic to any component", "Hypervitaminosis"],
    storage: ["Store below 25°C", "Protect from light", "Use within 30 days of opening"],
    price: { unit_price: 80.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/pedeamin.png",
    alternatives: [],
    created_at: "2025-04-01",
  },
  {
    id: "13",
    medicine_name: "Seclo 20",
    generic_name: "Omeprazole",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Gastric",
    type: "Capsule",
    description: "Seclo is a proton pump inhibitor used to treat gastroesophageal reflux disease (GERD), peptic ulcers, and Zollinger-Ellison syndrome.",
    usage: "Used for the treatment of duodenal ulcer, gastric ulcer, GERD, and erosive esophagitis.",
    dosage: { adult: "20mg once daily before breakfast for 4-8 weeks.", child: "Children over 1 year: 10-20mg once daily.", elderly: "No dose adjustment needed.", special_instructions: "Swallow whole. Do not crush or chew." },
    side_effects: { common: ["Headache", "Diarrhea", "Nausea", "Abdominal pain"], serious: ["Clostridium difficile colitis", "Bone fracture risk", "Hypomagnesemia"] },
    precautions: { pregnancy: "Category C. Use only if benefits outweigh risks.", kidney: "No dose adjustment in mild-moderate impairment.", liver: "Maximum 10mg/day in severe hepatic impairment.", allergy: "Contraindicated if allergic to benzimidazoles.", drug_interaction: "May reduce absorption of ketoconazole, iron salts, digoxin." },
    who_should_avoid: ["Hypersensitivity to omeprazole", "Concurrent use with rilpivirine"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 6.0, strip_price: 60, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/seclo.png",
    alternatives: ["3", "6"],
    created_at: "2025-01-20",
  },
  {
    id: "14",
    medicine_name: "Maxpro 20",
    generic_name: "Esomeprazole",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Gastric",
    type: "Capsule",
    description: "Maxpro contains Esomeprazole, a proton pump inhibitor for acid-related disorders including GERD and peptic ulcers.",
    usage: "Treatment of GERD, erosive esophagitis, H. pylori eradication therapy, and NSAID-associated gastric ulcers.",
    dosage: { adult: "20-40mg once daily for 4-8 weeks.", child: "12+ years: 20mg once daily.", elderly: "No dose adjustment required.", special_instructions: "Take at least 1 hour before meals." },
    side_effects: { common: ["Headache", "Flatulence", "Nausea", "Dry mouth"], serious: ["Interstitial nephritis", "Severe hypomagnesemia", "Lupus erythematosus"] },
    precautions: { pregnancy: "Category B. Use with caution.", kidney: "No dose adjustment needed.", liver: "Maximum 20mg/day in severe liver disease.", allergy: "Avoid if allergic to substituted benzimidazoles.", drug_interaction: "Interacts with clopidogrel, methotrexate, tacrolimus." },
    who_should_avoid: ["Known hypersensitivity", "Concurrent rilpivirine use"],
    storage: ["Store below 30°C", "Protect from light", "Keep in original packaging"],
    price: { unit_price: 7.0, strip_price: 70, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/maxpro.png",
    alternatives: ["3", "13"],
    created_at: "2025-01-22",
  },
  {
    id: "15",
    medicine_name: "Amoxil 500",
    generic_name: "Amoxicillin",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Antibiotics",
    type: "Capsule",
    description: "Amoxil is a broad-spectrum penicillin antibiotic used for the treatment of various bacterial infections.",
    usage: "Treatment of respiratory tract infections, urinary tract infections, skin infections, and ear infections.",
    dosage: { adult: "250-500mg every 8 hours or 500-875mg every 12 hours.", child: "20-40mg/kg/day in divided doses.", elderly: "Normal adult dose with renal adjustment.", special_instructions: "Complete the full course of treatment." },
    side_effects: { common: ["Diarrhea", "Nausea", "Skin rash", "Vomiting"], serious: ["Anaphylaxis", "Pseudomembranous colitis", "Stevens-Johnson syndrome"] },
    precautions: { pregnancy: "Category B. Generally considered safe.", kidney: "Dose reduction in severe renal impairment.", liver: "Use with caution in hepatic impairment.", allergy: "Contraindicated in penicillin allergy.", drug_interaction: "May reduce efficacy of oral contraceptives. Interacts with allopurinol." },
    who_should_avoid: ["Penicillin-allergic patients", "History of amoxicillin-associated cholestatic jaundice"],
    storage: ["Store below 25°C", "Keep dry", "Keep away from children"],
    price: { unit_price: 5.0, strip_price: 50, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/amoxil.png",
    alternatives: ["16"],
    created_at: "2025-01-25",
  },
  {
    id: "16",
    medicine_name: "Moxacil 500",
    generic_name: "Amoxicillin",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Antibiotics",
    type: "Capsule",
    description: "Moxacil is an aminopenicillin antibiotic effective against a wide range of gram-positive and gram-negative bacteria.",
    usage: "Treatment of otitis media, sinusitis, bronchitis, pneumonia, urinary tract infections, and skin infections.",
    dosage: { adult: "500mg every 8 hours.", child: "25-50mg/kg/day divided every 8 hours.", elderly: "Adjust based on renal function.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Diarrhea", "Stomach upset", "Headache"], serious: ["Severe allergic reaction", "Clostridium difficile colitis", "Hepatitis"] },
    precautions: { pregnancy: "Category B. Safe for use.", kidney: "Reduce dose in severe renal failure.", liver: "Monitor liver function.", allergy: "Do not use if allergic to penicillins.", drug_interaction: "Interacts with methotrexate and warfarin." },
    who_should_avoid: ["Penicillin allergy", "Mononucleosis patients"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep out of reach of children"],
    price: { unit_price: 4.5, strip_price: 45, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/moxacil.png",
    alternatives: ["15"],
    created_at: "2025-01-28",
  },
  {
    id: "17",
    medicine_name: "Ciprocin 500",
    generic_name: "Ciprofloxacin",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Antibiotics",
    type: "Tablet",
    description: "Ciprocin is a fluoroquinolone antibiotic used to treat various bacterial infections including UTI, respiratory, and gastrointestinal infections.",
    usage: "Treatment of urinary tract infections, respiratory infections, bone and joint infections, and typhoid fever.",
    dosage: { adult: "250-750mg twice daily for 7-14 days.", child: "Not recommended for children under 18.", elderly: "Reduced dose based on renal function.", special_instructions: "Take with plenty of water. Avoid dairy products within 2 hours." },
    side_effects: { common: ["Nausea", "Diarrhea", "Dizziness", "Headache"], serious: ["Tendon rupture", "Peripheral neuropathy", "QT prolongation", "Aortic aneurysm"] },
    precautions: { pregnancy: "Category C. Avoid during pregnancy.", kidney: "Dose adjustment required.", liver: "Use with caution.", allergy: "Avoid if allergic to fluoroquinolones.", drug_interaction: "Interacts with theophylline, warfarin, antacids, and NSAIDs." },
    who_should_avoid: ["Children under 18", "Pregnant women", "Patients with tendon disorders", "Myasthenia gravis patients"],
    storage: ["Store below 30°C", "Keep away from light", "Keep away from children"],
    price: { unit_price: 6.0, strip_price: 60, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/ciprocin.png",
    alternatives: [],
    created_at: "2025-02-01",
  },
  {
    id: "18",
    medicine_name: "Fluconazole 150",
    generic_name: "Fluconazole",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Antibiotics",
    type: "Capsule",
    description: "Fluconazole is a triazole antifungal agent used for treatment of various fungal infections.",
    usage: "Treatment of vaginal candidiasis, oropharyngeal candidiasis, cryptococcal meningitis, and systemic candidiasis.",
    dosage: { adult: "150mg single dose for vaginal candidiasis; 200-400mg daily for systemic infections.", child: "3-12mg/kg/day based on infection.", elderly: "Adjust based on renal function.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Headache", "Nausea", "Abdominal pain", "Diarrhea"], serious: ["Hepatotoxicity", "QT prolongation", "Severe skin reactions", "Anaphylaxis"] },
    precautions: { pregnancy: "Category D. Avoid unless life-threatening infection.", kidney: "Reduce dose in renal impairment.", liver: "Use with caution. Monitor LFTs.", allergy: "Avoid if allergic to azole antifungals.", drug_interaction: "Major interactions with warfarin, phenytoin, rifampin, and statins." },
    who_should_avoid: ["Pregnancy (high dose)", "Severe liver disease", "QT prolongation risk"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep in original packaging"],
    price: { unit_price: 30.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/fluconazole.png",
    alternatives: [],
    created_at: "2025-02-05",
  },
  {
    id: "19",
    medicine_name: "Monas 10",
    generic_name: "Montelukast",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Allergy",
    type: "Tablet",
    description: "Monas is a leukotriene receptor antagonist used for the management of asthma and allergic rhinitis.",
    usage: "Prevention and chronic treatment of asthma, exercise-induced bronchoconstriction, and seasonal allergic rhinitis.",
    dosage: { adult: "10mg once daily in the evening.", child: "6-14 years: 5mg chewable tablet daily. 2-5 years: 4mg granules daily.", elderly: "No dose adjustment needed.", special_instructions: "Take in the evening. Continue even when asymptomatic." },
    side_effects: { common: ["Headache", "Abdominal pain", "Cough", "Dental pain"], serious: ["Neuropsychiatric events", "Eosinophilic conditions", "Anaphylaxis", "Angioedema"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "No adjustment required.", liver: "Use with caution in hepatic impairment.", allergy: "Avoid if hypersensitive to montelukast.", drug_interaction: "CYP inducers like phenobarbital may reduce effectiveness." },
    who_should_avoid: ["Phenylketonuria (chewable tablets contain phenylalanine)", "Acute asthma attacks"],
    storage: ["Store below 25°C", "Protect from moisture and light", "Keep away from children"],
    price: { unit_price: 8.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/monas.png",
    alternatives: [],
    created_at: "2025-02-10",
  },
  {
    id: "20",
    medicine_name: "Amlodipine 5",
    generic_name: "Amlodipine Besylate",
    company_name: "Eskayef Pharmaceuticals",
    company_id: "8",
    category: "Heart Care",
    type: "Tablet",
    description: "Amlodipine is a calcium channel blocker used for the treatment of hypertension and angina pectoris.",
    usage: "Treatment of high blood pressure, coronary artery disease, and chronic stable angina.",
    dosage: { adult: "5-10mg once daily.", child: "2.5-5mg once daily for children 6-17 years.", elderly: "Start with 2.5mg daily.", special_instructions: "Take at the same time each day. Do not stop suddenly." },
    side_effects: { common: ["Peripheral edema", "Dizziness", "Flushing", "Fatigue"], serious: ["Severe hypotension", "Heart failure worsening", "Hepatitis"] },
    precautions: { pregnancy: "Category C. Use only if benefits outweigh risks.", kidney: "No dose adjustment needed.", liver: "Start with 2.5mg in hepatic impairment.", allergy: "Avoid if allergic to dihydropyridines.", drug_interaction: "CYP3A4 inhibitors may increase levels. Interacts with simvastatin." },
    who_should_avoid: ["Severe aortic stenosis", "Cardiogenic shock", "Unstable angina"],
    storage: ["Store below 30°C", "Protect from light and moisture", "Keep away from children"],
    price: { unit_price: 3.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/amlodipine.png",
    alternatives: ["10"],
    created_at: "2025-02-15",
  },
  {
    id: "21",
    medicine_name: "Losartan 50",
    generic_name: "Losartan Potassium",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Heart Care",
    type: "Tablet",
    description: "Losartan is an angiotensin II receptor blocker (ARB) used for the treatment of hypertension and diabetic nephropathy.",
    usage: "Treatment of hypertension, diabetic nephropathy in type 2 diabetes, and stroke risk reduction.",
    dosage: { adult: "50mg once daily. May increase to 100mg.", child: "6+ years: 0.7mg/kg once daily (max 50mg).", elderly: "Start with lower dose.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Dizziness", "Upper respiratory infection", "Nasal congestion", "Back pain"], serious: ["Hyperkalemia", "Renal failure", "Angioedema", "Hepatotoxicity"] },
    precautions: { pregnancy: "Category D. Discontinue immediately if pregnancy detected.", kidney: "Use with caution in renal artery stenosis.", liver: "Reduce dose in hepatic impairment.", allergy: "Avoid if hypersensitive to ARBs.", drug_interaction: "NSAIDs may reduce effect. Risk of hyperkalemia with potassium supplements." },
    who_should_avoid: ["Pregnant women", "Bilateral renal artery stenosis", "Severe hepatic impairment"],
    storage: ["Store below 30°C", "Protect from light", "Keep in dry place"],
    price: { unit_price: 5.0, strip_price: 50, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/losartan.png",
    alternatives: ["10"],
    created_at: "2025-02-18",
  },
  {
    id: "22",
    medicine_name: "Metformin 500",
    generic_name: "Metformin Hydrochloride",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Diabetes",
    type: "Tablet",
    description: "Metformin is a biguanide antidiabetic agent used as first-line treatment for type 2 diabetes mellitus.",
    usage: "Treatment of type 2 diabetes, either alone or in combination with other antidiabetic agents including insulin.",
    dosage: { adult: "500mg twice daily with meals. Maximum 2550mg/day.", child: "10+ years: 500mg twice daily. Max 2000mg/day.", elderly: "Start conservatively. Monitor renal function.", special_instructions: "Take with meals to reduce GI side effects." },
    side_effects: { common: ["Nausea", "Diarrhea", "Abdominal discomfort", "Metallic taste"], serious: ["Lactic acidosis", "Vitamin B12 deficiency", "Hypoglycemia (with other agents)"] },
    precautions: { pregnancy: "Category B. May be used in gestational diabetes.", kidney: "Contraindicated if eGFR <30. Avoid initiation if eGFR 30-45.", liver: "Avoid in hepatic impairment.", allergy: "Avoid if hypersensitive.", drug_interaction: "Contrast media may cause lactic acidosis. Interacts with alcohol." },
    who_should_avoid: ["Severe renal impairment", "Metabolic acidosis", "Heavy alcohol users", "Severe heart failure"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/metformin.png",
    alternatives: ["23"],
    created_at: "2025-02-20",
  },
  {
    id: "23",
    medicine_name: "Glimepiride 2",
    generic_name: "Glimepiride",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Diabetes",
    type: "Tablet",
    description: "Glimepiride is a sulfonylurea antidiabetic agent that stimulates insulin secretion from the pancreas.",
    usage: "Adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus.",
    dosage: { adult: "1-2mg once daily with breakfast. Maximum 8mg/day.", child: "Not recommended.", elderly: "Start with 1mg daily.", special_instructions: "Take with the first main meal. Do not skip meals." },
    side_effects: { common: ["Hypoglycemia", "Dizziness", "Nausea", "Weight gain"], serious: ["Severe hypoglycemia", "Hemolytic anemia", "Hepatic porphyria", "SIADH"] },
    precautions: { pregnancy: "Category C. Switch to insulin during pregnancy.", kidney: "Start with 1mg in renal impairment.", liver: "Use with caution.", allergy: "Avoid if allergic to sulfonamides.", drug_interaction: "Beta-blockers may mask hypoglycemia. NSAIDs may enhance effect." },
    who_should_avoid: ["Type 1 diabetes", "Diabetic ketoacidosis", "Sulfonamide allergy"],
    storage: ["Store below 30°C", "Protect from light", "Keep in original container"],
    price: { unit_price: 4.0, strip_price: 40, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/glimepiride.png",
    alternatives: ["22"],
    created_at: "2025-02-22",
  },
  {
    id: "24",
    medicine_name: "Atorva 10",
    generic_name: "Atorvastatin",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Heart Care",
    type: "Tablet",
    description: "Atorva is an HMG-CoA reductase inhibitor (statin) used for lowering cholesterol and reducing cardiovascular risk.",
    usage: "Treatment of primary hypercholesterolemia, mixed dyslipidemia, and prevention of cardiovascular disease.",
    dosage: { adult: "10-80mg once daily. Usual starting dose 10-20mg.", child: "10-17 years: 10mg once daily.", elderly: "No dose adjustment needed.", special_instructions: "Can be taken at any time of day, with or without food." },
    side_effects: { common: ["Muscle pain", "Joint pain", "Diarrhea", "Nasopharyngitis"], serious: ["Rhabdomyolysis", "Hepatotoxicity", "Immune-mediated necrotizing myopathy"] },
    precautions: { pregnancy: "Category X. Contraindicated in pregnancy.", kidney: "No dose adjustment required.", liver: "Contraindicated in active liver disease.", allergy: "Avoid if hypersensitive to statins.", drug_interaction: "CYP3A4 inhibitors increase levels. Avoid grapefruit juice." },
    who_should_avoid: ["Pregnant/nursing women", "Active liver disease", "Unexplained elevated transaminases"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 5.0, strip_price: 50, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/atorva.png",
    alternatives: [],
    created_at: "2025-02-25",
  },
  {
    id: "25",
    medicine_name: "Clopid 75",
    generic_name: "Clopidogrel",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Heart Care",
    type: "Tablet",
    description: "Clopid is an antiplatelet agent that prevents blood clot formation in coronary artery disease and stroke.",
    usage: "Prevention of atherosclerotic events in patients with recent MI, stroke, or established peripheral arterial disease.",
    dosage: { adult: "75mg once daily. Loading dose of 300mg for acute coronary syndrome.", child: "Not recommended.", elderly: "No dose adjustment needed.", special_instructions: "Take at the same time each day. Inform surgeon before any surgery." },
    side_effects: { common: ["Bleeding", "Bruising", "Diarrhea", "Abdominal pain"], serious: ["Thrombotic thrombocytopenic purpura", "GI hemorrhage", "Intracranial hemorrhage"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "Use with caution.", liver: "Avoid in severe hepatic impairment.", allergy: "Avoid if allergic to thienopyridines.", drug_interaction: "Omeprazole reduces effectiveness. NSAIDs increase bleeding risk." },
    who_should_avoid: ["Active bleeding", "Severe liver impairment", "Upcoming surgery within 7 days"],
    storage: ["Store below 25°C", "Keep away from light", "Keep in dry place"],
    price: { unit_price: 6.0, strip_price: 60, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/clopid.png",
    alternatives: [],
    created_at: "2025-02-28",
  },
  {
    id: "26",
    medicine_name: "Pantonix 40",
    generic_name: "Pantoprazole",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Gastric",
    type: "Tablet",
    description: "Pantonix is a proton pump inhibitor used for acid-related gastrointestinal disorders.",
    usage: "Treatment of GERD, erosive esophagitis, Zollinger-Ellison syndrome, and H. pylori eradication.",
    dosage: { adult: "40mg once daily for 4-8 weeks.", child: "5+ years, >40kg: 40mg daily.", elderly: "No dose adjustment needed.", special_instructions: "Swallow whole. Take before breakfast." },
    side_effects: { common: ["Headache", "Diarrhea", "Nausea", "Flatulence"], serious: ["C. difficile infection", "Bone fractures", "Lupus erythematosus", "Fundic gland polyps"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "No adjustment in mild-moderate impairment.", liver: "Maximum 20mg/day in severe hepatic disease.", allergy: "Avoid if allergic to benzimidazoles.", drug_interaction: "May affect absorption of pH-dependent drugs. Interacts with methotrexate." },
    who_should_avoid: ["Hypersensitivity to PPIs", "Concurrent rilpivirine use"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep in original blister"],
    price: { unit_price: 7.0, strip_price: 70, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/pantonix.png",
    alternatives: ["3", "13", "14"],
    created_at: "2025-03-01",
  },
  {
    id: "27",
    medicine_name: "Tycil 500",
    generic_name: "Cephalexin",
    company_name: "Opsonin Pharma",
    company_id: "5",
    category: "Antibiotics",
    type: "Capsule",
    description: "Tycil is a first-generation cephalosporin antibiotic used for treating various bacterial infections.",
    usage: "Treatment of respiratory tract, urinary tract, skin and soft tissue, bone, and middle ear infections.",
    dosage: { adult: "250-500mg every 6 hours. Maximum 4g/day.", child: "25-50mg/kg/day in divided doses.", elderly: "Adjust based on renal function.", special_instructions: "Complete full course. Take with food to reduce GI upset." },
    side_effects: { common: ["Diarrhea", "Nausea", "Dyspepsia", "Abdominal pain"], serious: ["Pseudomembranous colitis", "Anaphylaxis", "Stevens-Johnson syndrome", "Seizures"] },
    precautions: { pregnancy: "Category B. Generally safe.", kidney: "Reduce dose in renal impairment.", liver: "Use with caution.", allergy: "Cross-reactivity possible with penicillin allergy (1-10%).", drug_interaction: "Probenecid increases levels. May affect warfarin response." },
    who_should_avoid: ["Cephalosporin allergy", "History of cephalosporin-related colitis"],
    storage: ["Store below 25°C", "Keep dry", "Keep away from children"],
    price: { unit_price: 8.0, strip_price: 80, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/tycil.png",
    alternatives: [],
    created_at: "2025-03-05",
  },
  {
    id: "28",
    medicine_name: "Doxicap 100",
    generic_name: "Doxycycline",
    company_name: "ACI Limited",
    company_id: "7",
    category: "Antibiotics",
    type: "Capsule",
    description: "Doxicap is a tetracycline antibiotic with broad-spectrum activity against many bacterial and protozoal infections.",
    usage: "Treatment of acne, respiratory infections, urinary tract infections, sexually transmitted infections, and malaria prophylaxis.",
    dosage: { adult: "100mg twice daily on day 1, then 100mg once daily.", child: "Over 8 years: 2-4mg/kg/day.", elderly: "No dose adjustment needed.", special_instructions: "Take with plenty of water. Remain upright for 30 minutes after taking." },
    side_effects: { common: ["Nausea", "Photosensitivity", "Diarrhea", "Esophageal irritation"], serious: ["Pseudotumor cerebri", "Hepatotoxicity", "C. difficile colitis", "Severe skin reactions"] },
    precautions: { pregnancy: "Category D. Avoid during pregnancy.", kidney: "No dose adjustment needed.", liver: "Use with caution in hepatic impairment.", allergy: "Avoid if allergic to tetracyclines.", drug_interaction: "Antacids and iron reduce absorption. Enhances warfarin effect." },
    who_should_avoid: ["Children under 8", "Pregnant women", "Severe hepatic dysfunction"],
    storage: ["Store below 30°C", "Protect from light and moisture", "Keep away from children"],
    price: { unit_price: 5.0, strip_price: 50, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/doxicap.png",
    alternatives: [],
    created_at: "2025-03-08",
  },
  {
    id: "29",
    medicine_name: "Levoflox 500",
    generic_name: "Levofloxacin",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Antibiotics",
    type: "Tablet",
    description: "Levoflox is a fluoroquinolone antibiotic used for treating respiratory, urinary, and skin infections.",
    usage: "Treatment of community-acquired pneumonia, acute bacterial sinusitis, UTI, and chronic bacterial prostatitis.",
    dosage: { adult: "250-750mg once daily for 7-14 days.", child: "Not recommended for children.", elderly: "Dose adjustment based on renal function.", special_instructions: "Take with plenty of fluids. Avoid sunlight exposure." },
    side_effects: { common: ["Nausea", "Headache", "Diarrhea", "Insomnia"], serious: ["Tendon rupture", "Peripheral neuropathy", "Aortic dissection", "Hypoglycemia"] },
    precautions: { pregnancy: "Category C. Avoid during pregnancy.", kidney: "Dose adjustment required for CrCl <50.", liver: "No dose adjustment needed.", allergy: "Avoid if allergic to quinolones.", drug_interaction: "Antacids reduce absorption. Interacts with warfarin and theophylline." },
    who_should_avoid: ["Children under 18", "Pregnant/nursing women", "History of tendon disorders", "Epilepsy"],
    storage: ["Store below 25°C", "Protect from light", "Keep in original packaging"],
    price: { unit_price: 12.0, strip_price: 120, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/levoflox.png",
    alternatives: ["17"],
    created_at: "2025-03-10",
  },
  {
    id: "30",
    medicine_name: "Ranitidine 150",
    generic_name: "Ranitidine Hydrochloride",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Gastric",
    type: "Tablet",
    description: "Ranitidine is an H2 receptor antagonist that reduces stomach acid production for treating ulcers and GERD.",
    usage: "Treatment of duodenal ulcers, gastric ulcers, GERD, Zollinger-Ellison syndrome, and heartburn.",
    dosage: { adult: "150mg twice daily or 300mg at bedtime.", child: "2-16 years: 2-4mg/kg twice daily.", elderly: "No dose adjustment needed.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Headache", "Constipation", "Diarrhea", "Nausea"], serious: ["Hepatitis", "Blood dyscrasias", "Anaphylaxis", "Pneumonia"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "Reduce dose in severe renal impairment.", liver: "Use with caution.", allergy: "Avoid if allergic to H2 blockers.", drug_interaction: "May affect absorption of ketoconazole, atazanavir." },
    who_should_avoid: ["Porphyria", "Known hypersensitivity"],
    storage: ["Store below 30°C", "Protect from light", "Keep in dry place"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/ranitidine.png",
    alternatives: ["26"],
    created_at: "2025-03-12",
  },
  {
    id: "31",
    medicine_name: "Ventolin Inhaler",
    generic_name: "Salbutamol",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Allergy",
    type: "Inhaler",
    description: "Ventolin is a short-acting beta-2 agonist bronchodilator used for relief and prevention of bronchospasm.",
    usage: "Relief of bronchospasm in asthma, COPD, and exercise-induced bronchoconstriction.",
    dosage: { adult: "1-2 puffs (100-200mcg) every 4-6 hours as needed.", child: "1 puff every 4-6 hours as needed.", elderly: "Same as adult dose.", special_instructions: "Shake well before use. Rinse mouth after use." },
    side_effects: { common: ["Tremor", "Headache", "Tachycardia", "Nervousness"], serious: ["Paradoxical bronchospasm", "Severe hypokalemia", "Cardiac arrhythmias"] },
    precautions: { pregnancy: "Category C. Use only if benefits outweigh risks.", kidney: "No dose adjustment needed.", liver: "No dose adjustment needed.", allergy: "Avoid if allergic to salbutamol.", drug_interaction: "Beta-blockers may reduce effectiveness. MAOIs and TCAs increase cardiovascular effects." },
    who_should_avoid: ["Known hypersensitivity", "Untreated hypokalemia"],
    storage: ["Store below 30°C", "Do not freeze", "Keep away from heat sources", "Keep away from children"],
    price: { unit_price: 120.0, strip_price: 120, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/ventolin.png",
    alternatives: [],
    created_at: "2025-03-15",
  },
  {
    id: "32",
    medicine_name: "Cetirizine 10",
    generic_name: "Cetirizine Hydrochloride",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Allergy",
    type: "Tablet",
    description: "Cetirizine is a second-generation antihistamine used for allergic rhinitis and chronic urticaria.",
    usage: "Treatment of seasonal and perennial allergic rhinitis, chronic idiopathic urticaria, and allergic conjunctivitis.",
    dosage: { adult: "10mg once daily.", child: "6-12 years: 5mg twice daily or 10mg once daily. 2-5 years: 2.5mg twice daily.", elderly: "5mg once daily if renal impairment.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Drowsiness", "Dry mouth", "Fatigue", "Headache"], serious: ["Anaphylaxis", "Seizures", "Hepatitis", "Glomerulonephritis"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "Reduce dose in moderate-severe renal impairment.", liver: "Reduce dose in hepatic impairment.", allergy: "Avoid if allergic to cetirizine or hydroxyzine.", drug_interaction: "CNS depressants and alcohol may enhance sedation." },
    who_should_avoid: ["Severe renal impairment (without dose adjustment)", "End-stage renal disease on dialysis"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 3.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/cetirizine.png",
    alternatives: ["8"],
    created_at: "2025-03-18",
  },
  {
    id: "33",
    medicine_name: "Prednisolone 5",
    generic_name: "Prednisolone",
    company_name: "Opsonin Pharma",
    company_id: "5",
    category: "Allergy",
    type: "Tablet",
    description: "Prednisolone is a corticosteroid used for its anti-inflammatory and immunosuppressive properties.",
    usage: "Treatment of allergic disorders, asthma, rheumatic disorders, inflammatory bowel disease, and autoimmune conditions.",
    dosage: { adult: "5-60mg/day depending on condition.", child: "0.5-2mg/kg/day.", elderly: "Use lowest effective dose.", special_instructions: "Take with food. Do not stop abruptly after prolonged use." },
    side_effects: { common: ["Weight gain", "Insomnia", "Mood changes", "Increased appetite"], serious: ["Adrenal suppression", "Osteoporosis", "Diabetes", "Immunosuppression", "Cataracts"] },
    precautions: { pregnancy: "Category C. Use only if benefits outweigh risks.", kidney: "Use with caution.", liver: "May need dose adjustment.", allergy: "Avoid if hypersensitive to corticosteroids.", drug_interaction: "NSAIDs increase GI bleeding risk. Reduces efficacy of vaccines." },
    who_should_avoid: ["Systemic fungal infections", "Live vaccine recipients", "Active tuberculosis"],
    storage: ["Store below 25°C", "Protect from light", "Keep in original container"],
    price: { unit_price: 1.0, strip_price: 10, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/prednisolone.png",
    alternatives: [],
    created_at: "2025-03-20",
  },
  {
    id: "34",
    medicine_name: "Diclofenac 50",
    generic_name: "Diclofenac Sodium",
    company_name: "ACI Limited",
    company_id: "7",
    category: "Pain Relief",
    type: "Tablet",
    description: "Diclofenac is a nonsteroidal anti-inflammatory drug (NSAID) used for pain and inflammation relief.",
    usage: "Treatment of osteoarthritis, rheumatoid arthritis, ankylosing spondylitis, acute pain, and primary dysmenorrhea.",
    dosage: { adult: "50mg 2-3 times daily. Maximum 150mg/day.", child: "1-3mg/kg/day in divided doses.", elderly: "Use lowest effective dose.", special_instructions: "Take with food or milk. Avoid lying down for 10 minutes after taking." },
    side_effects: { common: ["Abdominal pain", "Constipation", "Diarrhea", "Dizziness", "Headache"], serious: ["GI bleeding", "Myocardial infarction", "Stroke", "Renal failure", "Hepatotoxicity"] },
    precautions: { pregnancy: "Category C (D in 3rd trimester). Avoid in late pregnancy.", kidney: "Avoid in severe renal impairment.", liver: "Use with caution. Monitor LFTs.", allergy: "Contraindicated if aspirin-sensitive.", drug_interaction: "Increases lithium and methotrexate levels. Reduces antihypertensive effect." },
    who_should_avoid: ["Active GI bleeding", "Severe heart failure", "Perioperative CABG pain", "Aspirin-sensitive patients"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/diclofenac.png",
    alternatives: [],
    created_at: "2025-03-22",
  },
  {
    id: "35",
    medicine_name: "Ibuprofen 400",
    generic_name: "Ibuprofen",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Pain Relief",
    type: "Tablet",
    description: "Ibuprofen is a propionic acid derivative NSAID used for pain, inflammation, and fever reduction.",
    usage: "Treatment of mild to moderate pain, fever, dysmenorrhea, osteoarthritis, and rheumatoid arthritis.",
    dosage: { adult: "200-400mg every 4-6 hours. Maximum 1200mg/day (OTC).", child: "5-10mg/kg every 6-8 hours.", elderly: "Use lowest effective dose.", special_instructions: "Take with food or milk." },
    side_effects: { common: ["Nausea", "Dyspepsia", "Diarrhea", "Dizziness"], serious: ["GI bleeding", "Cardiovascular events", "Renal impairment", "Severe skin reactions"] },
    precautions: { pregnancy: "Category C (D in 3rd trimester).", kidney: "Avoid in severe renal disease.", liver: "Use with caution.", allergy: "Avoid if aspirin-sensitive.", drug_interaction: "Reduces effect of ACE inhibitors. Increases lithium levels." },
    who_should_avoid: ["Active GI bleeding", "Severe renal/hepatic failure", "Perioperative CABG pain"],
    storage: ["Store below 25°C", "Keep dry", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/ibuprofen.png",
    alternatives: ["34"],
    created_at: "2025-03-25",
  },
  {
    id: "36",
    medicine_name: "Traxyl 50",
    generic_name: "Tramadol Hydrochloride",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Pain Relief",
    type: "Capsule",
    description: "Traxyl is a centrally acting opioid analgesic used for moderate to moderately severe pain management.",
    usage: "Management of moderate to moderately severe pain when non-opioid analgesics are inadequate.",
    dosage: { adult: "50-100mg every 4-6 hours. Maximum 400mg/day.", child: "Not recommended under 12 years.", elderly: "Start with 25mg. Maximum 300mg/day in elderly >75.", special_instructions: "Can be taken with or without food. Do not crush extended-release forms." },
    side_effects: { common: ["Nausea", "Dizziness", "Constipation", "Headache", "Drowsiness"], serious: ["Seizures", "Serotonin syndrome", "Respiratory depression", "Anaphylaxis"] },
    precautions: { pregnancy: "Category C. Avoid in late pregnancy.", kidney: "Reduce dose in CrCl <30.", liver: "Reduce dose in cirrhosis.", allergy: "Avoid if allergic to opioids.", drug_interaction: "Dangerous with MAOIs, SSRIs, TCAs. CNS depressants enhance effects." },
    who_should_avoid: ["Epilepsy (uncontrolled)", "Concurrent MAOI use", "Acute intoxication", "Children under 12"],
    storage: ["Store below 25°C", "Keep in original container", "Keep away from children"],
    price: { unit_price: 5.0, strip_price: 50, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/traxyl.png",
    alternatives: [],
    created_at: "2025-03-28",
  },
  {
    id: "37",
    medicine_name: "Calcium-D",
    generic_name: "Calcium Carbonate + Vitamin D3",
    company_name: "Renata Limited",
    company_id: "4",
    category: "Vitamins",
    type: "Tablet",
    description: "Calcium-D is a combination supplement providing calcium and vitamin D3 for bone health.",
    usage: "Prevention and treatment of calcium and vitamin D deficiency, osteoporosis prevention, and bone health maintenance.",
    dosage: { adult: "1 tablet twice daily after meals.", child: "As directed by physician.", elderly: "1 tablet twice daily.", special_instructions: "Take after meals. Do not take with high-fiber foods." },
    side_effects: { common: ["Constipation", "Bloating", "Gas", "Nausea"], serious: ["Hypercalcemia", "Kidney stones", "Hypercalciuria"] },
    precautions: { pregnancy: "Safe in recommended doses.", kidney: "Avoid in severe renal impairment or kidney stones.", liver: "No dose adjustment needed.", allergy: "Avoid if allergic to any component.", drug_interaction: "Reduces absorption of tetracyclines, quinolones, bisphosphonates. Take 2 hours apart." },
    who_should_avoid: ["Hypercalcemia", "Kidney stones", "Vitamin D toxicity", "Severe renal impairment"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 5.0, strip_price: 75, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/calcium-d.png",
    alternatives: [],
    created_at: "2025-03-30",
  },
  {
    id: "38",
    medicine_name: "Filwel Gold",
    generic_name: "Multivitamin + Multimineral",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Vitamins",
    type: "Tablet",
    description: "Filwel Gold is a comprehensive multivitamin and multimineral supplement for daily nutritional support.",
    usage: "Dietary supplementation for vitamin and mineral deficiencies, post-illness recovery, and general health maintenance.",
    dosage: { adult: "1 tablet daily after a meal.", child: "Not recommended for children under 12.", elderly: "1 tablet daily.", special_instructions: "Take after the largest meal of the day." },
    side_effects: { common: ["Nausea", "Stomach upset", "Unpleasant taste", "Dark stool (iron)"], serious: ["Iron toxicity (overdose)", "Hypervitaminosis A (chronic excess)"] },
    precautions: { pregnancy: "Consult doctor. Excess Vitamin A is harmful.", kidney: "Avoid if severe renal disease.", liver: "Use with caution.", allergy: "Check all ingredients.", drug_interaction: "Iron reduces absorption of quinolones and tetracyclines." },
    who_should_avoid: ["Iron overload conditions", "Hypervitaminosis", "Children under 12"],
    storage: ["Store below 25°C", "Protect from light and moisture", "Keep in sealed container"],
    price: { unit_price: 10.0, strip_price: 150, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/filwel.png",
    alternatives: [],
    created_at: "2025-04-01",
  },
  {
    id: "39",
    medicine_name: "Ketoconazole Cream",
    generic_name: "Ketoconazole",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Skin Care",
    type: "Cream",
    description: "Ketoconazole cream is a topical antifungal used for treating various skin fungal infections.",
    usage: "Treatment of tinea corporis, tinea cruris, tinea versicolor, cutaneous candidiasis, and seborrheic dermatitis.",
    dosage: { adult: "Apply once or twice daily to affected area for 2-4 weeks.", child: "Same as adult dose.", elderly: "Same as adult dose.", special_instructions: "Clean and dry affected area before applying. Do not cover with bandage." },
    side_effects: { common: ["Skin irritation", "Itching", "Burning sensation", "Redness"], serious: ["Severe allergic reaction", "Contact dermatitis"] },
    precautions: { pregnancy: "Category C. Use only if clearly needed.", kidney: "Not applicable for topical use.", liver: "Not applicable for topical use.", allergy: "Avoid if allergic to azole antifungals.", drug_interaction: "Minimal systemic absorption. No significant interactions with topical use." },
    who_should_avoid: ["Known allergy to ketoconazole", "Open wounds"],
    storage: ["Store below 25°C", "Do not freeze", "Keep tube tightly closed"],
    price: { unit_price: 60.0, strip_price: 60, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/ketoconazole-cream.png",
    alternatives: ["11"],
    created_at: "2025-04-03",
  },
  {
    id: "40",
    medicine_name: "Betnovate-N",
    generic_name: "Betamethasone + Neomycin",
    company_name: "Eskayef Pharmaceuticals",
    company_id: "8",
    category: "Skin Care",
    type: "Cream",
    description: "Betnovate-N is a combination cream containing a potent corticosteroid and an antibiotic for inflammatory skin conditions with secondary bacterial infection.",
    usage: "Treatment of eczema, dermatitis, psoriasis, and other inflammatory skin conditions with bacterial infection risk.",
    dosage: { adult: "Apply thinly 2-3 times daily.", child: "Short-term use only. Apply thinly once daily.", elderly: "Use sparingly. Short-term use recommended.", special_instructions: "Apply thinly. Do not use on face for prolonged periods." },
    side_effects: { common: ["Burning", "Itching", "Skin thinning", "Stretch marks"], serious: ["Adrenal suppression", "Cushing syndrome", "Skin atrophy", "Secondary infection"] },
    precautions: { pregnancy: "Use with caution. Avoid large areas or prolonged use.", kidney: "Not applicable for topical use.", liver: "Not applicable for topical use.", allergy: "Avoid if allergic to steroids or neomycin.", drug_interaction: "Avoid concurrent use with other topical steroids." },
    who_should_avoid: ["Rosacea", "Acne", "Viral skin infections", "Fungal skin infections", "Children under 1"],
    storage: ["Store below 25°C", "Keep tube tightly closed", "Keep away from children"],
    price: { unit_price: 65.0, strip_price: 65, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/betnovate-n.png",
    alternatives: ["11"],
    created_at: "2025-04-05",
  },
  {
    id: "41",
    medicine_name: "Napa Syrup",
    generic_name: "Paracetamol",
    company_name: "Beximco Pharmaceuticals",
    company_id: "2",
    category: "Children Care",
    type: "Syrup",
    description: "Napa Syrup is a paracetamol suspension formulated for children, providing effective fever and pain relief.",
    usage: "Relief of mild to moderate pain and fever in children, including teething pain, post-vaccination fever, and cold symptoms.",
    dosage: { adult: "N/A - pediatric formulation.", child: "3 months-1yr: 2.5ml, 1-5yrs: 5ml, 6-12yrs: 10ml. Every 4-6 hours.", elderly: "N/A - pediatric formulation.", special_instructions: "Shake well before use. Use measuring spoon or syringe." },
    side_effects: { common: ["Nausea", "Vomiting", "Allergic skin rash"], serious: ["Hepatotoxicity (overdose)", "Severe skin reactions", "Blood dyscrasias"] },
    precautions: { pregnancy: "N/A - pediatric formulation.", kidney: "Reduce dose frequency in renal impairment.", liver: "Avoid in liver disease.", allergy: "Avoid if allergic to paracetamol.", drug_interaction: "Warfarin effect may be enhanced with regular use." },
    who_should_avoid: ["Known paracetamol allergy", "Severe liver disease", "Infants under 2 months (without medical advice)"],
    storage: ["Store below 25°C", "Keep away from sunlight", "Use within 6 months of opening"],
    price: { unit_price: 40.0, strip_price: 40, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/napa-syrup.png",
    alternatives: [],
    created_at: "2025-04-08",
  },
  {
    id: "42",
    medicine_name: "Aristophan DS",
    generic_name: "Paracetamol (Pediatric)",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Children Care",
    type: "Drops",
    description: "Aristophan DS is a pediatric paracetamol drop formulated for infants and young children for fever and pain.",
    usage: "Fever reduction and pain relief in infants and young children, including post-vaccination fever.",
    dosage: { adult: "N/A - pediatric formulation.", child: "0-3 months: 0.5ml, 3-12 months: 1ml, 1-2 years: 1.5ml every 4-6 hours.", elderly: "N/A.", special_instructions: "Use only the provided dropper. Do not exceed 4 doses in 24 hours." },
    side_effects: { common: ["Mild nausea", "Skin rash (rare)"], serious: ["Hepatotoxicity (overdose)", "Severe allergic reaction"] },
    precautions: { pregnancy: "N/A - pediatric formulation.", kidney: "Use with caution.", liver: "Avoid in liver disease.", allergy: "Avoid if allergic to paracetamol.", drug_interaction: "No significant interactions in pediatric doses." },
    who_should_avoid: ["Known paracetamol allergy", "Severe liver disease", "Neonates under 2 months (without medical advice)"],
    storage: ["Store below 25°C", "Keep away from light", "Use within 3 months of opening"],
    price: { unit_price: 25.0, strip_price: 25, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/aristophan.png",
    alternatives: ["41"],
    created_at: "2025-04-10",
  },
  {
    id: "43",
    medicine_name: "Omeprazole 20",
    generic_name: "Omeprazole",
    company_name: "Opsonin Pharma",
    company_id: "5",
    category: "Gastric",
    type: "Capsule",
    description: "Omeprazole is a proton pump inhibitor that reduces gastric acid secretion for treating acid-related disorders.",
    usage: "Treatment of peptic ulcer disease, GERD, Zollinger-Ellison syndrome, and NSAID-induced gastropathy.",
    dosage: { adult: "20-40mg once daily for 4-8 weeks.", child: "1mg/kg/day for children over 2.", elderly: "No dose adjustment needed.", special_instructions: "Take 30 minutes before breakfast." },
    side_effects: { common: ["Headache", "Diarrhea", "Abdominal pain", "Nausea"], serious: ["C. difficile colitis", "Bone fractures", "Hypomagnesemia", "Vitamin B12 deficiency"] },
    precautions: { pregnancy: "Category C. Use if benefits outweigh risks.", kidney: "No dose adjustment.", liver: "Maximum 20mg/day in severe liver disease.", allergy: "Avoid if allergic to PPIs.", drug_interaction: "Reduces absorption of ketoconazole, iron. Interacts with clopidogrel." },
    who_should_avoid: ["Known PPI allergy", "Concurrent rilpivirine use"],
    storage: ["Store below 25°C", "Protect from moisture", "Keep in original packaging"],
    price: { unit_price: 4.0, strip_price: 40, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/omeprazole.png",
    alternatives: ["3", "13"],
    created_at: "2025-04-12",
  },
  {
    id: "44",
    medicine_name: "Domperidone 10",
    generic_name: "Domperidone",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Gastric",
    type: "Tablet",
    description: "Domperidone is a prokinetic agent and antiemetic used for nausea, vomiting, and gastroparesis.",
    usage: "Treatment of nausea and vomiting, bloating, epigastric fullness, and gastroparesis.",
    dosage: { adult: "10mg three times daily before meals.", child: "0.25mg/kg three times daily.", elderly: "Use lowest effective dose.", special_instructions: "Take 15-30 minutes before meals." },
    side_effects: { common: ["Dry mouth", "Headache", "Diarrhea", "Drowsiness"], serious: ["QT prolongation", "Cardiac arrhythmias", "Galactorrhea", "Gynecomastia"] },
    precautions: { pregnancy: "Use only if clearly needed.", kidney: "Reduce dose frequency.", liver: "Contraindicated in moderate-severe hepatic impairment.", allergy: "Avoid if hypersensitive.", drug_interaction: "CYP3A4 inhibitors increase risk. Avoid with QT-prolonging drugs." },
    who_should_avoid: ["Prolactinoma", "Hepatic impairment", "Cardiac conduction disorders", "GI hemorrhage"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/domperidone.png",
    alternatives: [],
    created_at: "2025-04-15",
  },
  {
    id: "45",
    medicine_name: "Azifast 500",
    generic_name: "Azithromycin",
    company_name: "Healthcare Pharmaceuticals",
    company_id: "6",
    category: "Antibiotics",
    type: "Tablet",
    description: "Azifast is a macrolide antibiotic used for treating respiratory, skin, ear, and sexually transmitted infections.",
    usage: "Treatment of community-acquired pneumonia, pharyngitis, otitis media, skin infections, and chlamydial infections.",
    dosage: { adult: "500mg on day 1, then 250mg daily for days 2-5.", child: "10mg/kg on day 1, then 5mg/kg for days 2-5.", elderly: "No dose adjustment needed.", special_instructions: "Take 1 hour before or 2 hours after meals." },
    side_effects: { common: ["Diarrhea", "Nausea", "Abdominal pain", "Vomiting"], serious: ["Hepatotoxicity", "QT prolongation", "C. difficile colitis", "Angioedema"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "Use with caution in GFR <10.", liver: "Avoid in severe liver disease.", allergy: "Avoid if allergic to macrolides.", drug_interaction: "Antacids reduce absorption. Interacts with warfarin and digoxin." },
    who_should_avoid: ["Macrolide allergy", "History of cholestatic jaundice with azithromycin", "Severe liver disease"],
    storage: ["Store below 30°C", "Keep dry", "Complete full course"],
    price: { unit_price: 25.0, strip_price: 75, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/azifast.png",
    alternatives: ["4", "5"],
    created_at: "2025-04-18",
  },
  {
    id: "46",
    medicine_name: "Insulin Mixtard 30",
    generic_name: "Insulin Human (30/70)",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Diabetes",
    type: "Injection",
    description: "Insulin Mixtard 30 is a premixed insulin containing 30% soluble insulin and 70% isophane insulin for diabetes management.",
    usage: "Treatment of type 1 and type 2 diabetes mellitus when oral agents are insufficient.",
    dosage: { adult: "Individualized. Usually 0.5-1 unit/kg/day.", child: "Individualized based on body weight.", elderly: "Start with lower doses.", special_instructions: "Inject subcutaneously. Rotate injection sites. Do not mix with other insulins." },
    side_effects: { common: ["Hypoglycemia", "Injection site reactions", "Weight gain", "Lipodystrophy"], serious: ["Severe hypoglycemia", "Hypokalemia", "Anaphylaxis"] },
    precautions: { pregnancy: "Safe for use in pregnancy.", kidney: "May need dose reduction.", liver: "May need dose reduction.", allergy: "Rarely allergic to human insulin.", drug_interaction: "Beta-blockers mask hypoglycemia signs. Corticosteroids increase insulin need." },
    who_should_avoid: ["Hypoglycemia episodes", "Known insulin allergy"],
    storage: ["Refrigerate 2-8°C unopened", "Room temperature up to 6 weeks after opening", "Do not freeze"],
    price: { unit_price: 400.0, strip_price: 400, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/mixtard.png",
    alternatives: ["9"],
    created_at: "2025-04-20",
  },
  {
    id: "47",
    medicine_name: "Cefixime 200",
    generic_name: "Cefixime",
    company_name: "Eskayef Pharmaceuticals",
    company_id: "8",
    category: "Antibiotics",
    type: "Capsule",
    description: "Cefixime is a third-generation oral cephalosporin antibiotic with broad-spectrum activity.",
    usage: "Treatment of urinary tract infections, otitis media, pharyngitis, tonsillitis, bronchitis, and gonorrhea.",
    dosage: { adult: "200mg twice daily or 400mg once daily.", child: "8mg/kg/day in 1-2 divided doses.", elderly: "No dose adjustment in normal renal function.", special_instructions: "Can be taken with or without food." },
    side_effects: { common: ["Diarrhea", "Loose stools", "Abdominal pain", "Nausea"], serious: ["Pseudomembranous colitis", "Severe allergic reaction", "Stevens-Johnson syndrome"] },
    precautions: { pregnancy: "Category B. Use only if needed.", kidney: "Reduce dose in severe renal impairment.", liver: "No dose adjustment.", allergy: "Cross-reactivity with penicillin possible.", drug_interaction: "Probenecid increases cefixime levels. May enhance warfarin effect." },
    who_should_avoid: ["Cephalosporin allergy", "History of cephalosporin-associated colitis"],
    storage: ["Store below 30°C", "Keep dry", "Keep away from children"],
    price: { unit_price: 15.0, strip_price: 150, currency: "BDT", updated_date: "2025-05-15" },
    image: "/medicines/cefixime.png",
    alternatives: [],
    created_at: "2025-04-22",
  },
  {
    id: "48",
    medicine_name: "Lisinopril 5",
    generic_name: "Lisinopril",
    company_name: "Square Pharmaceuticals",
    company_id: "1",
    category: "Heart Care",
    type: "Tablet",
    description: "Lisinopril is an ACE inhibitor used for the treatment of hypertension, heart failure, and post-MI management.",
    usage: "Treatment of hypertension, heart failure, acute myocardial infarction, and diabetic nephropathy.",
    dosage: { adult: "5-40mg once daily.", child: "6+ years: 0.07mg/kg once daily.", elderly: "Start with 2.5-5mg daily.", special_instructions: "Take at the same time each day." },
    side_effects: { common: ["Cough", "Dizziness", "Headache", "Fatigue"], serious: ["Angioedema", "Hyperkalemia", "Renal failure", "Hepatic failure"] },
    precautions: { pregnancy: "Category D. Discontinue if pregnant.", kidney: "Reduce dose in renal impairment.", liver: "Use with caution.", allergy: "Avoid if history of ACE inhibitor angioedema.", drug_interaction: "NSAIDs reduce effect. Risk of hyperkalemia with potassium-sparing diuretics." },
    who_should_avoid: ["Pregnancy", "History of angioedema", "Bilateral renal artery stenosis"],
    storage: ["Store below 30°C", "Protect from moisture", "Keep away from children"],
    price: { unit_price: 3.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/lisinopril.png",
    alternatives: ["21"],
    created_at: "2025-04-25",
  },
  {
    id: "49",
    medicine_name: "Clonazepam 0.5",
    generic_name: "Clonazepam",
    company_name: "Incepta Pharmaceuticals",
    company_id: "3",
    category: "Fever",
    type: "Tablet",
    description: "Clonazepam is a benzodiazepine used for seizure disorders and panic disorder.",
    usage: "Treatment of epilepsy (Lennox-Gastaut syndrome, akinetic and myoclonic seizures), panic disorder with or without agoraphobia.",
    dosage: { adult: "0.5mg three times daily. Maximum 20mg/day for seizures.", child: "0.01-0.03mg/kg/day in 2-3 divided doses.", elderly: "Start with 0.25mg twice daily.", special_instructions: "Do not stop abruptly. Taper gradually." },
    side_effects: { common: ["Drowsiness", "Ataxia", "Behavioral changes", "Fatigue"], serious: ["Respiratory depression", "Suicidal ideation", "Severe withdrawal", "Paradoxical reactions"] },
    precautions: { pregnancy: "Category D. Avoid unless essential.", kidney: "Use with caution.", liver: "Reduce dose in hepatic impairment.", allergy: "Avoid if allergic to benzodiazepines.", drug_interaction: "CNS depressants enhance effects. Opioids increase respiratory depression risk." },
    who_should_avoid: ["Acute narrow-angle glaucoma", "Severe liver disease", "Sleep apnea", "Myasthenia gravis"],
    storage: ["Store below 30°C", "Protect from light", "Keep in original container", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 30, currency: "BDT", updated_date: "2025-05-18" },
    image: "/medicines/clonazepam.png",
    alternatives: [],
    created_at: "2025-04-28",
  },
  {
    id: "50",
    medicine_name: "Zinc 20",
    generic_name: "Zinc Sulfate",
    company_name: "ACI Limited",
    company_id: "7",
    category: "Children Care",
    type: "Tablet",
    description: "Zinc 20 is a zinc supplement recommended by WHO for the management of acute diarrhea in children.",
    usage: "Adjunctive treatment of acute diarrhea in children, zinc deficiency, and immune support.",
    dosage: { adult: "20mg once daily for diarrhea (10-14 days).", child: "Under 6 months: 10mg daily. 6 months-5 years: 20mg daily for 10-14 days.", elderly: "20mg daily if deficient.", special_instructions: "Dissolve in breast milk or water for infants." },
    side_effects: { common: ["Nausea", "Vomiting", "Metallic taste", "Abdominal cramps"], serious: ["Copper deficiency (chronic high dose)", "GI irritation"] },
    precautions: { pregnancy: "Safe in recommended doses.", kidney: "Accumulation risk in severe renal failure.", liver: "Use with caution in hepatic disease.", allergy: "Avoid if allergic to zinc.", drug_interaction: "Reduces absorption of quinolones, tetracyclines, penicillamine." },
    who_should_avoid: ["Known zinc allergy", "Severe renal failure without monitoring"],
    storage: ["Store below 30°C", "Keep dry", "Keep away from children"],
    price: { unit_price: 2.0, strip_price: 20, currency: "BDT", updated_date: "2025-05-20" },
    image: "/medicines/zinc.png",
    alternatives: [],
    created_at: "2025-04-30",
  },
];

export const companies: Company[] = [
  {
    id: "1",
    name: "Square Pharmaceuticals",
    logo: "/companies/square.png",
    about: "Square Pharmaceuticals Ltd. is the largest pharmaceutical company in Bangladesh. Established in 1958, it has been serving the nation with quality medicines for over 6 decades. The company manufactures and markets a wide range of pharmaceutical products.",
    total_medicines: 850,
    categories: ["Antibiotics", "Pain Relief", "Gastric", "Vitamins", "Heart Care", "Diabetes"],
    popular_products: ["Ace Plus", "Sergel 20", "Zimax 500", "Neuro-B"],
    founded: "1958",
    headquarters: "Pabna, Bangladesh",
  },
  {
    id: "2",
    name: "Beximco Pharmaceuticals",
    logo: "/companies/beximco.png",
    about: "Beximco Pharmaceuticals Ltd. is one of the leading pharmaceutical companies in Bangladesh, known for manufacturing high-quality medicines at affordable prices. Listed on both Dhaka and London Stock Exchanges.",
    total_medicines: 620,
    categories: ["Pain Relief", "Antibiotics", "Vitamins", "Skin Care", "Gastric"],
    popular_products: ["Napa Extra", "Napa", "Neofloxin", "Dexoren"],
    founded: "1976",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "3",
    name: "Incepta Pharmaceuticals",
    logo: "/companies/incepta.png",
    about: "Incepta Pharmaceuticals Ltd. is one of the fastest-growing pharmaceutical companies in Bangladesh. Known for innovation and quality, Incepta manufactures a wide range of dosage forms including tablets, capsules, injectables, and more.",
    total_medicines: 750,
    categories: ["Antibiotics", "Diabetes", "Heart Care", "Gastric", "Allergy"],
    popular_products: ["Azicin 500", "Losectil 20", "Insulet N"],
    founded: "1999",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "4",
    name: "Renata Limited",
    logo: "/companies/renata.png",
    about: "Renata Limited is a leading Bangladeshi pharmaceutical company committed to improving healthcare through innovative medicines and animal health products. Known for strict quality standards and ethical practices.",
    total_medicines: 480,
    categories: ["Heart Care", "Allergy", "Antibiotics", "Pain Relief", "Vitamins"],
    popular_products: ["Fexo 120", "Cardipro 5"],
    founded: "1972",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "5",
    name: "Opsonin Pharma",
    logo: "/companies/opsonin.png",
    about: "Opsonin Pharma Limited is a prominent pharmaceutical manufacturer in Bangladesh, producing a diverse portfolio of medicines. The company is known for its commitment to quality and affordable healthcare.",
    total_medicines: 380,
    categories: ["Skin Care", "Pain Relief", "Antibiotics", "Gastric"],
    popular_products: ["Dermovate"],
    founded: "1956",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "6",
    name: "Healthcare Pharmaceuticals",
    logo: "/companies/healthcare.png",
    about: "Healthcare Pharmaceuticals Ltd. specializes in producing quality pharmaceutical products with a focus on pediatric care and specialized medicines for the Bangladesh market.",
    total_medicines: 320,
    categories: ["Children Care", "Vitamins", "Pain Relief", "Fever"],
    popular_products: ["Pedeamin"],
    founded: "1986",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "7",
    name: "ACI Limited",
    logo: "/companies/aci.png",
    about: "ACI Limited is a diversified conglomerate with a strong presence in the pharmaceutical sector. ACI Pharma produces a wide range of quality medicines serving millions of patients across Bangladesh.",
    total_medicines: 350,
    categories: ["Antibiotics", "Pain Relief", "Heart Care", "Diabetes", "Vitamins"],
    popular_products: ["ACI Paracetamol", "ACI Omeprazole"],
    founded: "1968",
    headquarters: "Dhaka, Bangladesh",
  },
  {
    id: "8",
    name: "Eskayef Pharmaceuticals",
    logo: "/companies/eskayef.png",
    about: "Eskayef Pharmaceuticals Ltd. is a leading pharmaceutical company in Bangladesh, known for producing world-class quality medicines. A subsidiary of Transcom Group, Eskayef has earned trust through decades of service.",
    total_medicines: 420,
    categories: ["Antibiotics", "Gastric", "Heart Care", "Pain Relief", "Allergy"],
    popular_products: ["Esoral", "Atova"],
    founded: "1940",
    headquarters: "Dhaka, Bangladesh",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "understanding-antibiotic-resistance",
    title: "Understanding Antibiotic Resistance: A Growing Concern",
    excerpt: "Learn about the growing threat of antibiotic resistance and how to use antibiotics responsibly to protect public health.",
    content: `Antibiotic resistance is one of the biggest threats to global health, food security, and development. It occurs when bacteria change in response to the use of antibiotic medicines.\n\nAntibiotic resistance happens naturally, but misuse of antibiotics in humans and animals is accelerating the process. A growing number of infections are becoming harder to treat as the antibiotics used to treat them become less effective.\n\n## What Causes Antibiotic Resistance?\n\n1. **Overuse of antibiotics** - Taking antibiotics when they're not needed\n2. **Not completing the full course** - Stopping treatment early\n3. **Self-medication** - Using leftover antibiotics without prescription\n4. **Use in agriculture** - Excessive use in livestock farming\n\n## How to Prevent Antibiotic Resistance\n\n- Only use antibiotics when prescribed by a doctor\n- Always complete the full prescription\n- Never share antibiotics with others\n- Prevent infections through good hygiene\n- Keep vaccinations up to date\n\nBy being responsible with antibiotic use, we can help slow down resistance and ensure these life-saving medicines remain effective for future generations.`,
    category: "Drug Awareness",
    image: "/blog/antibiotic-resistance.jpg",
    author: "Dr. Rahman",
    date: "2025-05-15",
    read_time: "5 min read",
  },
  {
    id: "2",
    slug: "managing-diabetes-with-lifestyle",
    title: "Managing Diabetes Through Lifestyle Changes",
    excerpt: "Discover how diet, exercise, and lifestyle modifications can significantly impact diabetes management alongside medication.",
    content: `Diabetes management is more than just taking medication. Lifestyle changes play a crucial role in controlling blood sugar levels and preventing complications.\n\n## Diet Management\n\n- Choose complex carbohydrates over simple sugars\n- Include plenty of fiber in your diet\n- Control portion sizes\n- Eat at regular intervals\n\n## Exercise Benefits\n\nRegular physical activity helps your body use insulin more effectively. Aim for at least 150 minutes of moderate exercise per week.\n\n## Stress Management\n\nStress hormones can raise blood sugar levels. Practice relaxation techniques like deep breathing, meditation, or yoga.\n\n## Regular Monitoring\n\nKeep track of your blood sugar levels and maintain regular check-ups with your healthcare provider. This helps in early detection of any complications.`,
    category: "Health Tips",
    image: "/blog/diabetes-lifestyle.jpg",
    author: "Dr. Karim",
    date: "2025-05-10",
    read_time: "7 min read",
  },
  {
    id: "3",
    slug: "medicine-storage-guide",
    title: "How to Store Medicines Safely at Home",
    excerpt: "A comprehensive guide on proper medicine storage to ensure safety and maintain medication effectiveness.",
    content: `Proper storage of medicines is essential for maintaining their effectiveness and ensuring safety.\n\n## General Storage Tips\n\n1. **Cool, dry place** - Most medicines should be stored below 25°C\n2. **Away from sunlight** - UV light can degrade medications\n3. **Out of reach of children** - Use child-proof containers\n4. **Original packaging** - Keep medicines in their original containers\n\n## Refrigerated Medicines\n\nSome medicines like insulin need refrigeration (2-8°C). Never freeze unless specified.\n\n## Medicine Cabinet Organization\n\n- Check expiry dates regularly\n- Dispose of expired medicines properly\n- Keep a list of all medications\n- Separate adult and children's medicines\n\n## What NOT to Do\n\n- Don't store medicines in the bathroom (humidity)\n- Don't transfer medicines to different containers\n- Don't keep medicines in direct sunlight\n- Don't store medicines near heat sources`,
    category: "Medicine Safety",
    image: "/blog/medicine-storage.jpg",
    author: "Pharmacist Hasan",
    date: "2025-05-05",
    read_time: "4 min read",
  },
  {
    id: "4",
    slug: "importance-of-generic-medicines",
    title: "Generic Medicines: Same Quality, Lower Cost",
    excerpt: "Understanding why generic medicines are equally effective as brand-name drugs and how they can save you money.",
    content: `Generic medicines contain the same active ingredients as their brand-name counterparts and are equally safe and effective.\n\n## What Makes Generics the Same?\n\n- **Same active ingredient** - Identical chemical composition\n- **Same dosage** - Equal strength and form\n- **Same quality standards** - Must meet regulatory requirements\n- **Bioequivalent** - Absorbed at the same rate\n\n## Why Are They Cheaper?\n\nGeneric manufacturers don't have the cost of drug discovery and clinical trials, allowing them to offer the same medicine at significantly lower prices.\n\n## Bangladesh's Generic Medicine Industry\n\nBangladesh has a thriving generic pharmaceutical industry that provides affordable medicines to millions. The industry is recognized globally for quality manufacturing.`,
    category: "Healthcare Education",
    image: "/blog/generic-medicines.jpg",
    author: "Dr. Sultana",
    date: "2025-04-28",
    read_time: "6 min read",
  },
  {
    id: "5",
    slug: "common-drug-interactions",
    title: "Common Drug Interactions You Should Know About",
    excerpt: "Learn about dangerous drug interactions and how to safely manage multiple medications.",
    content: `Drug interactions can change how your medications work or increase the risk of serious side effects.\n\n## Types of Interactions\n\n### Drug-Drug Interactions\nWhen two or more drugs react with each other. Example: Blood thinners with aspirin.\n\n### Drug-Food Interactions\nSome foods can affect how drugs work. Example: Grapefruit with statins.\n\n### Drug-Condition Interactions\nCertain medical conditions can make some drugs harmful. Example: Aspirin in patients with bleeding disorders.\n\n## How to Prevent Interactions\n\n1. Tell your doctor about all medications you take\n2. Use one pharmacy for all prescriptions\n3. Read medication labels carefully\n4. Ask about potential interactions before starting new medicines\n5. Never mix medications without medical advice`,
    category: "Drug Awareness",
    image: "/blog/drug-interactions.jpg",
    author: "Dr. Ahmed",
    date: "2025-04-20",
    read_time: "5 min read",
  },
  {
    id: "6",
    slug: "pediatric-medicine-safety",
    title: "Giving Medicine to Children: A Parent's Guide",
    excerpt: "Essential tips for safely administering medicine to children, including dosage calculation and common mistakes to avoid.",
    content: `Giving medicine to children requires extra care and attention. Here's what every parent should know.\n\n## Dosage Guidelines\n\n- Always use the measuring device provided\n- Never use household spoons for liquid medicines\n- Follow weight-based dosing, not age-based\n- Never give adult medicines to children\n\n## Common Mistakes\n\n1. **Wrong dosage** - Always double-check measurements\n2. **Wrong timing** - Maintain consistent intervals\n3. **Stopping early** - Complete the full course\n4. **Self-prescribing** - Always consult a pediatrician\n\n## Making Medicine Time Easier\n\n- Use flavored medicines when available\n- Mix liquid medicines with a small amount of food\n- Praise children after taking medicine\n- Explain why the medicine is important in simple terms`,
    category: "Health Tips",
    image: "/blog/pediatric-safety.jpg",
    author: "Dr. Fatima",
    date: "2025-04-15",
    read_time: "6 min read",
  },
];

export function searchMedicines(query: string): Medicine[] {
  const q = query.toLowerCase().trim();
  if (!q) return medicines;
  return medicines.filter(
    (m) =>
      m.medicine_name.toLowerCase().includes(q) ||
      m.generic_name.toLowerCase().includes(q) ||
      m.company_name.toLowerCase().includes(q) ||
      m.category.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.type.toLowerCase().includes(q)
  );
}

export function getMedicineById(id: string): Medicine | undefined {
  return medicines.find((m) => m.id === id);
}

export function getCompanyById(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}

export function getMedicinesByCompany(companyId: string): Medicine[] {
  return medicines.filter((m) => m.company_id === companyId);
}

export function getMedicinesByCategory(category: string): Medicine[] {
  return medicines.filter((m) => m.category.toLowerCase() === category.toLowerCase());
}

export function getBlogBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((b) => b.slug === slug);
}

export function getAlternativeMedicines(medicine: Medicine): Medicine[] {
  return medicine.alternatives
    .map((id) => medicines.find((m) => m.id === id))
    .filter((m): m is Medicine => m !== undefined);
}

export const trendingSearches = [
  "Napa Extra",
  "Sergel",
  "Azithromycin",
  "Omeprazole",
  "Paracetamol",
  "Fexofenadine",
  "Vitamin B",
  "Insulin",
];
